#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/Alchemist
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/127550/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/467768/

static const AttackEffect alchemist_data_0[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 24300,
        .period = 12000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 1792, 5, 0},
    },
};
static const AttackCurvePoint alchemist_data_1[] = {
    {0},
    {.x = 1, .y = 17},
    {.x = 2, .y = 34},
    {.x = 3, .y = 50},
    {.x = 4, .y = 66},
    {.x = 5, .y = 81},
    {.x = 6, .y = 95},
    {.x = 7, .y = 109},
    {.x = 8, .y = 122},
    {.x = 9, .y = 134},
    {.x = 10, .y = 146},
    {.x = 11, .y = 157},
    {.x = 12, .y = 168},
    {.x = 13, .y = 178},
    {.x = 14, .y = 188},
    {.x = 15, .y = 196},
    {.x = 16, .y = 205},
    {.x = 17, .y = 212},
    {.x = 18, .y = 219},
    {.x = 19, .y = 226},
    {.x = 20, .y = 231},
    {.x = 21, .y = 237},
    {.x = 22, .y = 241},
    {.x = 23, .y = 245},
    {.x = 24, .y = 248},
    {.x = 25, .y = 251},
    {.x = 26, .y = 253},
    {.x = 27, .y = 255},
    {.x = 28, .y = 256},
    {.x = 29, .y = 256},
};
static const AttackDef alchemist_data_2[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 1792,
        .damage = 1,
        .pierce = 5,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 12000,
        .status_time = 24300,
        .status_layers = 65535,
        .effects = alchemist_data_0,
        .effect_count = 2,
        .flags = A_AREA | A_DOT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_3[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 27300,
        .period = 9000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 1792, 5, 0},
    },
};
static const AttackDef alchemist_data_4[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 1792,
        .damage = 1,
        .pierce = 5,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 9000,
        .status_time = 27300,
        .status_layers = 65535,
        .effects = alchemist_data_3,
        .effect_count = 2,
        .flags = A_AREA | A_DOT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_5[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 27300,
        .period = 9000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 4,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 15,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 5,
        .chance = 1000,
        .modifier_flags = 8,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 4,
        .mutation = MUT_NONE,
        .exclude_tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 1792, 5, 0},
    },
};
static const AttackDef alchemist_data_6[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 1792,
        .damage = 1,
        .pierce = 5,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 9000,
        .status_time = 27300,
        .status_layers = 65535,
        .moab = 4,
        .effects = alchemist_data_5,
        .effect_count = 5,
        .flags = A_AREA | A_DOT | A_DEFORT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackDamageSource alchemist_data_7[] = {
    {.source_tag = 4096, .bloon_damage = 4, .moab_damage = 400},
    {.source_tag = 512, .bloon_damage = 3, .moab_damage = 70},
    {.source_tag = 2048, .bloon_damage = 4, .moab_damage = 40},
    {.source_tag = 256, .bloon_damage = 2, .moab_damage = 20},
    {.source_tag = 1024, .bloon_damage = 4, .moab_damage = 400},
};
static const AttackEffect alchemist_data_8[] = {
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 256,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 512,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .tags = 1024,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 9,
        .mutation = MUT_NONE,
        .tags = 4096,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .tags = 2048,
        .chance = 1000,
    },
};
static const AttackDef alchemist_data_9[] = {
    {
        .life = 300,
        .range = 17280,
        .radius = 10240,
        .pierce = 50,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_POP,
        .source_damage = alchemist_data_7,
        .source_damage_count = 5,
        .default_bloon_damage = 4,
        .default_moab_damage = 20,
        .motion_flags = 2113,
        .effects = alchemist_data_8,
        .effect_count = 5,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_10[] = {
    {
        .kind = EF_CONCOCTION,
        .flags = EF_UNIQUE,
        .layers = 2,
        .multiplier = 1000,
        .time = 4294967295,
        .mutation = MUT_UNSTABLE,
    },
};
static const AttackDef alchemist_data_11[] = {
    {
        .life = 300,
        .range = 17280,
        .radius = 3584,
        .pierce = 3,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .motion_flags = 2113,
        .children = alchemist_data_9,
        .child_count = 1,
        .effects = alchemist_data_10,
        .effect_count = 1,
        .flags = A_MOAB_ONLY | A_AREA | A_CONCOCTION,
        .target_flags = AT_NO_CONCOCTION | AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_12[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 24300,
        .period = 12000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 2688, 10, 0},
    },
};
static const AttackDef alchemist_data_13[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 2688,
        .damage = 1,
        .pierce = 10,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 12000,
        .status_time = 24300,
        .status_layers = 65535,
        .effects = alchemist_data_12,
        .effect_count = 2,
        .flags = A_AREA | A_DOT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_14[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 27300,
        .period = 9000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 2688, 10, 0},
    },
};
static const AttackDef alchemist_data_15[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 2688,
        .damage = 1,
        .pierce = 10,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 9000,
        .status_time = 27300,
        .status_layers = 65535,
        .effects = alchemist_data_14,
        .effect_count = 2,
        .flags = A_AREA | A_DOT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect alchemist_data_16[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 27300,
        .period = 9000,
        .value = 16398,
        .mutation = MUT_ACID,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 4,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 15,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 5,
        .chance = 1000,
        .modifier_flags = 8,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 4,
        .mutation = MUT_NONE,
        .exclude_tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_ACID_POOL,
        .multiplier = 1000,
        .time = 300,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 2688, 10, 0},
    },
};
static const AttackDef alchemist_data_17[] = {
    {
        .life = 300,
        .range = 11520,
        .radius = 2688,
        .damage = 1,
        .pierce = 10,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .immunity = 64,
        .motion_flags = 2113,
        .dot_damage = 1,
        .dot_period = 9000,
        .status_time = 27300,
        .status_layers = 65535,
        .moab = 4,
        .effects = alchemist_data_16,
        .effect_count = 5,
        .flags = A_AREA | A_DOT | A_DEFORT | A_ACID,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackDef alchemist_data_18[] = {
    {
        .life = 300,
        .range = 17280,
        .radius = 5376,
        .pierce = 4,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .motion_flags = 2113,
        .children = alchemist_data_9,
        .child_count = 1,
        .effects = alchemist_data_10,
        .effect_count = 1,
        .flags = A_MOAB_ONLY | A_AREA | A_CONCOCTION,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const Upgrade alchemist_data_19[] = {
    {.name = "Larger Potions", .price = 250, .icon = 97},
    {.name = "Acidic Mixture Dip", .price = 350, .icon = 98},
    {.name = "Berserker Brew", .price = 1400, .icon = 99},
    {.name = "Stronger Stimulant", .price = 2850, .icon = 100},
};
static const Upgrade alchemist_data_20[] = {
    {.name = "Stronger Acid", .price = 250, .icon = 101},
    {.name = "Perishing Potions", .price = 475, .icon = 102},
    {.name = "Unstable Concoction", .price = 2800, .icon = 103},
};
static const TowerProfile
    alchemist_data_21[] =
        {
            {
                .tiers = {0, 0, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_2,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 1, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_4,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 2, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_6,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_6,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 36000,
                            .range = 17280,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 7,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_11,
                            .child_count = 1,
                            .flags = A_MOAB_ONLY | A_RETURN,
                            .target_flags = AT_NO_CONCOCTION | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 0, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_13,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 1, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_15,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 2, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 3, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 36000,
                            .range = 17280,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 7,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_18,
                            .child_count = 1,
                            .flags = A_MOAB_ONLY | A_RETURN,
                            .target_flags = AT_NO_CONCOCTION | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 0, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_13,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 1, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_15,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 2, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 12,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 3, 0},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 12,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 36000,
                            .range = 17280,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 7,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_18,
                            .child_count = 1,
                            .flags = A_MOAB_ONLY | A_RETURN,
                            .target_flags = AT_NO_CONCOCTION | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {3, 0, 0},
                .range = 11520,
                .buff_speed = 900,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 30000,
                .buff_block_time = 30000,
                .buff_damage = 1,
                .buff_pierce = 2,
                .buff_range_multiplier = 1100,
                .buff_shots = 25,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_13,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {3, 1, 0},
                .range = 11520,
                .buff_speed = 900,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 30000,
                .buff_block_time = 30000,
                .buff_damage = 1,
                .buff_pierce = 2,
                .buff_range_multiplier = 1100,
                .buff_shots = 25,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_15,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {3, 2, 0},
                .range = 11520,
                .buff_speed = 900,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 12,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 36000,
                .buff_block_time = 24000,
                .buff_damage = 1,
                .buff_pierce = 2,
                .buff_range_multiplier = 1100,
                .buff_shots = 40,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {4, 0, 0},
                .range = 11520,
                .buff_speed = 850,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 72000,
                .buff_block_time = 30000,
                .buff_damage = 1,
                .buff_pierce = 3,
                .buff_range_multiplier = 1150,
                .buff_shots = 40,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_13,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {4, 1, 0},
                .range = 11520,
                .buff_speed = 850,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 10,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 72000,
                .buff_block_time = 30000,
                .buff_damage = 1,
                .buff_pierce = 3,
                .buff_range_multiplier = 1150,
                .buff_shots = 40,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_15,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {4, 2, 0},
                .range = 11520,
                .buff_speed = 850,
                .footprint = 1536,
                .support = S_ALCHEMIST,
                .acid_period = 60000,
                .acid_shots = 12,
                .acid_cap = 30,
                .buff_throw_speed = 64000,
                .buff_period = 48000,
                .buff_time = 78000,
                .buff_block_time = 24000,
                .buff_damage = 1,
                .buff_pierce = 3,
                .buff_range_multiplier = 1150,
                .buff_shots = 55,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 11520,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = alchemist_data_1,
                            .curve_count = 30,
                            .children = alchemist_data_17,
                            .child_count = 1,
                            .flags = A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
};

const TowerDef alchemist_def = {
    .name = "Alchemist",
    .price = 550,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = alchemist_data_21,
    .upgrades = {alchemist_data_19, alchemist_data_20, NULL},
};
