#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/BombShooter
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/128136/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/344685/

static const AttackDef bomb_shooter_data_0[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 3072,
        .damage = 1,
        .pierce = 22,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_1[] = {
    {
        .life = 600,
        .range = 11264,
        .radius = 3072,
        .damage = 1,
        .pierce = 22,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackEffect bomb_shooter_data_2[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 15,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackDef bomb_shooter_data_3[] = {
    {
        .life = 600,
        .range = 12544,
        .radius = 3072,
        .damage = 1,
        .pierce = 22,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .moab = 15,
        .effects = bomb_shooter_data_2,
        .effect_count = 1,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_4[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 4608,
        .damage = 1,
        .pierce = 28,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_5[] = {
    {
        .life = 600,
        .range = 11264,
        .radius = 4608,
        .damage = 1,
        .pierce = 28,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_6[] = {
    {
        .life = 600,
        .range = 12544,
        .radius = 4608,
        .damage = 1,
        .pierce = 28,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .moab = 15,
        .effects = bomb_shooter_data_2,
        .effect_count = 1,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_7[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 4608,
        .damage = 2,
        .pierce = 38,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_8[] = {
    {
        .life = 600,
        .range = 11264,
        .radius = 4608,
        .damage = 2,
        .pierce = 38,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .flags = A_AREA,
    },
};
static const AttackDef bomb_shooter_data_9[] = {
    {
        .life = 600,
        .range = 12544,
        .radius = 4608,
        .damage = 2,
        .pierce = 38,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .moab = 15,
        .effects = bomb_shooter_data_2,
        .effect_count = 1,
        .flags = A_AREA,
    },
};
static const AttackEffect bomb_shooter_data_10[] = {
    {
        .kind = EF_PUSH,
        .flags = EF_ONLY_DAMAGED,
        .multiplier = 1000,
        .value = 5120,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 0, 0, 0},
    },
};
static const AttackDef bomb_shooter_data_11[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 6912,
        .damage = 4,
        .pierce = 80,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .push = 5120,
        .effects = bomb_shooter_data_10,
        .effect_count = 1,
        .flags = A_AREA | A_PUSH,
    },
};
static const AttackDef bomb_shooter_data_12[] = {
    {
        .life = 600,
        .range = 11264,
        .radius = 6912,
        .damage = 4,
        .pierce = 80,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .push = 5120,
        .effects = bomb_shooter_data_10,
        .effect_count = 1,
        .flags = A_AREA | A_PUSH,
    },
};
static const AttackEffect bomb_shooter_data_13[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .time = 8400,
        .mutation = MUT_STUN,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_STUN,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 2,
    },
    {
        .kind = EF_PUSH,
        .flags = EF_ONLY_DAMAGED,
        .multiplier = 1000,
        .value = 5120,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 0, 0, 0},
    },
};
static const AttackDef bomb_shooter_data_14[] = {
    {
        .life = 600,
        .range = 11008,
        .radius = 6912,
        .damage = 4,
        .pierce = 80,
        .count = 1,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .status_time = 8400,
        .status_layers = 65535,
        .push = 5120,
        .effects = bomb_shooter_data_13,
        .effect_count = 3,
        .flags = A_AREA | A_STUN | A_PUSH,
    },
};
static const AttackDef bomb_shooter_data_15[] = {
    {
        .life = 600,
        .range = 12032,
        .radius = 6912,
        .damage = 4,
        .pierce = 80,
        .count = 1,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .expire_rounds = 1,
        .motion_flags = 2113,
        .status_time = 8400,
        .status_layers = 65535,
        .push = 5120,
        .effects = bomb_shooter_data_13,
        .effect_count = 3,
        .flags = A_AREA | A_STUN | A_PUSH,
    },
};
static const Upgrade bomb_shooter_data_16[] = {
    {.name = "Bigger Bombs", .price = 250, .icon = 15},
    {.name = "Heavy Bombs", .price = 650, .icon = 16},
    {.name = "Really Big Bombs", .price = 1100, .icon = 17},
    {.name = "Bloon Impact", .price = 2800, .icon = 18},
};
static const Upgrade bomb_shooter_data_17[] = {
    {.name = "Faster Reload", .price = 250, .icon = 19},
    {.name = "Missile Launcher", .price = 400, .icon = 20},
    {.name = "MOAB Mauler", .price = 1000, .icon = 21},
};
static const TowerProfile bomb_shooter_data_18[] = {
    {
        .tiers = {0, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9000,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_0,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {0, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6750,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_0,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {0, 2, 0},
        .range = 11264,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 11264,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_1,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {0, 3, 0},
        .range = 12544,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 12544,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_3,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9000,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_4,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {1, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6750,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_4,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {1, 2, 0},
        .range = 11264,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 11264,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_5,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {1, 3, 0},
        .range = 12544,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 12544,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_6,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9000,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_7,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {2, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6750,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_7,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {2, 2, 0},
        .range = 11264,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 11264,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_8,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {2, 3, 0},
        .range = 12544,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 12544,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_9,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9000,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_11,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {3, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6750,
                    .life = 3600,
                    .range = 10240,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_11,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {3, 2, 0},
        .range = 11264,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 11264,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_12,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 11008,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9000,
                    .life = 3600,
                    .range = 11008,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_14,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {4, 1, 0},
        .range = 11008,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6750,
                    .life = 3600,
                    .range = 11008,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 46080,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_14,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
    {
        .tiers = {4, 2, 0},
        .range = 12032,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 4950,
                    .life = 3600,
                    .range = 12032,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 69120,
                    .motion_flags = 64,
                    .children = bomb_shooter_data_15,
                    .child_count = 1,
                    .flags = A_EXPLOSION,
                },
            },
    },
};

const TowerDef bomb_shooter_def = {
    .name = "Bomb Shooter",
    .price = 375,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = bomb_shooter_data_18,
    .upgrades = {bomb_shooter_data_16, bomb_shooter_data_17, NULL},
};
