#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/DartlingGunner
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153843/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/467956/

static const AttackDef dartling_gunner_data_0[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 2048,
        .damage = 2,
        .pierce = 6,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_PIERCE,
        .interval = 200,
        .camo = 1,
        .target_kind = 2,
        .fixed_target = 1,
        .motion_flags = 3137,
        .flags = A_AREA,
        .target_flags = AT_GLOBAL,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 2048,
        .damage = 2,
        .pierce = 6,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_BLOCKER,
        .camo = 1,
        .target_kind = 2,
        .fixed_target = 1,
        .motion_flags = 3137,
        .flags = A_AREA,
        .target_flags = AT_GLOBAL,
    },
};
static const AttackEffect dartling_gunner_data_1[] = {
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect dartling_gunner_data_2[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 65535,
        .damage = 1,
        .immunity = 17,
        .multiplier = 1000,
        .time = 6000,
        .period = 5700,
        .value = 8803,
        .mutation = MUT_LASER_SHOCK,
    },
    {
        .kind = EF_SHOCK_BONUS,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_LASER_SHOCK,
        .chance = 1000,
    },
};
static const AttackEffect dartling_gunner_data_3[] = {
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 65535,
        .damage = 1,
        .multiplier = 1000,
        .time = 6000,
        .period = 5700,
        .value = 8803,
        .mutation = MUT_LASER_SHOCK,
    },
    {
        .kind = EF_SHOCK_BONUS,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_LASER_SHOCK,
        .chance = 1000,
    },
};
static const AttackEffect dartling_gunner_data_4[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 65535,
        .damage = 1,
        .immunity = 73,
        .multiplier = 1000,
        .time = 12000,
        .period = 5700,
        .value = 55748,
        .mutation = MUT_LASER_SHOCK,
    },
    {
        .kind = EF_SHOCK_BONUS,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_LASER_SHOCK,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackEffect dartling_gunner_data_5[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 10,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 65535,
        .damage = 1,
        .immunity = 72,
        .multiplier = 1000,
        .time = 30000,
        .period = 5700,
        .value = 21309,
        .mutation = MUT_LASER_SHOCK,
    },
    {
        .kind = EF_SHOCK_BONUS,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_LASER_SHOCK,
        .chance = 1000,
    },
};
static const AttackDef dartling_gunner_data_6[] = {
    {
        .life = 360,
        .range = 65535,
        .radius = 1024,
        .damage = 2,
        .pierce = 50,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_BEAM_END,
        .target_kind = 2,
        .fixed_target = 1,
        .immunity = 72,
        .motion_flags = 2113,
        .moab = 10,
        .dot_damage = 1,
        .dot_period = 5700,
        .status_time = 30000,
        .status_layers = 65535,
        .status_cascade = 1,
        .effects = dartling_gunner_data_5,
        .effect_count = 3,
        .flags = A_AREA | A_DOT,
        .target_flags = AT_GLOBAL,
    },
};
static const AttackEffect dartling_gunner_data_7[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 65535,
        .damage = 1,
        .immunity = 72,
        .multiplier = 1000,
        .time = 30000,
        .period = 5700,
        .value = 21309,
        .mutation = MUT_LASER_SHOCK,
    },
    {
        .kind = EF_SHOCK_BONUS,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_LASER_SHOCK,
        .chance = 1000,
    },
};
static const AttackDef dartling_gunner_data_8[] = {
    {
        .life = 360,
        .range = 65535,
        .radius = 1024,
        .damage = 2,
        .pierce = 50,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_BEAM_END,
        .camo = 1,
        .target_kind = 2,
        .fixed_target = 1,
        .immunity = 72,
        .motion_flags = 2113,
        .moab = 10,
        .dot_damage = 1,
        .dot_period = 5700,
        .status_time = 30000,
        .status_layers = 65535,
        .status_cascade = 1,
        .effects = dartling_gunner_data_5,
        .effect_count = 3,
        .flags = A_AREA | A_DOT,
        .target_flags = AT_GLOBAL,
    },
};
static const Upgrade dartling_gunner_data_9[] = {
    {.name = "Focused Firing", .price = 300, .icon = 69},
    {.name = "Laser Shock", .price = 900, .icon = 70},
    {.name = "Laser Cannon", .price = 3000, .icon = 71},
    {.name = "Plasma Accelerator", .price = 11750, .icon = 72},
};
static const Upgrade dartling_gunner_data_10[] = {
    {.name = "Advanced Targeting", .price = 250, .icon = 73},
    {.name = "Faster Barrel Spin", .price = 950, .icon = 74},
    {.name = "Hydra Rocket Pods", .price = 4500, .icon = 75},
};
static const TowerProfile dartling_gunner_data_11[] = {
    {
        .tiers = {0, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 6857,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 23000,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {0, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 6857,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 23000,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {0, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 6857,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 23000,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {0, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 6857,
                    .range = 65535,
                    .radius = 768,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 23000,
                    .emission_kind = 2,
                    .speed = 89600,
                    .motion_flags = 64,
                    .children = dartling_gunner_data_0,
                    .child_count = 2,
                    .effects = dartling_gunner_data_1,
                    .effect_count = 1,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {1, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {1, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {1, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 9600,
                    .range = 65535,
                    .radius = 768,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .emission_kind = 2,
                    .speed = 89600,
                    .motion_flags = 64,
                    .children = dartling_gunner_data_0,
                    .child_count = 2,
                    .effects = dartling_gunner_data_1,
                    .effect_count = 1,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 6000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .effects = dartling_gunner_data_2,
                    .effect_count = 2,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {2, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 6000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .effects = dartling_gunner_data_2,
                    .effect_count = 2,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {2, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 9600,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 6000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .effects = dartling_gunner_data_2,
                    .effect_count = 2,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {2, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 9600,
                    .range = 65535,
                    .radius = 768,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .emission_kind = 2,
                    .speed = 89600,
                    .motion_flags = 64,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 6000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .children = dartling_gunner_data_0,
                    .child_count = 2,
                    .effects = dartling_gunner_data_3,
                    .effect_count = 3,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 6720,
                    .range = 65535,
                    .radius = 768,
                    .damage = 2,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 73,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 12000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .moab = 2,
                    .effects = dartling_gunner_data_4,
                    .effect_count = 3,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {3, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 6720,
                    .range = 65535,
                    .radius = 768,
                    .damage = 2,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 73,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 12000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .moab = 2,
                    .effects = dartling_gunner_data_4,
                    .effect_count = 3,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {3, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 6720,
                    .range = 65535,
                    .radius = 768,
                    .damage = 2,
                    .pierce = 6,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .random_spread = 9200,
                    .immunity = 73,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 12000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .moab = 2,
                    .effects = dartling_gunner_data_4,
                    .effect_count = 3,
                    .flags = A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 300,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 50,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .immunity = 72,
                    .speed = 92160,
                    .motion_flags = 2113,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 30000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .children = dartling_gunner_data_6,
                    .child_count = 1,
                    .effects = dartling_gunner_data_7,
                    .effect_count = 2,
                    .flags = A_BEAM | A_AREA | A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {4, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1200,
                    .life = 300,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 50,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .immunity = 72,
                    .speed = 92160,
                    .motion_flags = 2113,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 30000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .children = dartling_gunner_data_8,
                    .child_count = 1,
                    .effects = dartling_gunner_data_7,
                    .effect_count = 2,
                    .flags = A_BEAM | A_AREA | A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
    {
        .tiers = {4, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1792,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 792,
                    .life = 300,
                    .range = 65535,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 50,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 2,
                    .fixed_target = 1,
                    .immunity = 72,
                    .speed = 92160,
                    .motion_flags = 2113,
                    .dot_damage = 1,
                    .dot_period = 5700,
                    .status_time = 30000,
                    .status_layers = 65535,
                    .status_cascade = 1,
                    .children = dartling_gunner_data_8,
                    .child_count = 1,
                    .effects = dartling_gunner_data_7,
                    .effect_count = 2,
                    .flags = A_BEAM | A_AREA | A_DOT,
                    .target_flags = AT_GLOBAL,
                },
            },
    },
};

const TowerDef dartling_gunner_def = {
    .name = "Dartling Gunner",
    .price = 850,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = dartling_gunner_data_11,
    .upgrades = {dartling_gunner_data_9, dartling_gunner_data_10, NULL},
};
