#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/DartMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153842/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339149/

static const AttackEffect dart_monkey_data_0[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 3,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
    {
        .kind = EF_KNOCKBACK,
        .multiplier = 1000,
        .time = 900,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 2000, 4000, 0},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
};
static const AttackEffect dart_monkey_data_1[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 3,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
    {
        .kind = EF_KNOCKBACK,
        .multiplier = 1000,
        .time = 900,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {0, 3000, 6000, 0},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
};
static const Upgrade dart_monkey_data_2[] = {
    {
        .name = "Sharp Shots",
        .price = 140,
    },
    {.name = "Razor Sharp Shots", .price = 200, .icon = 1},
    {.name = "Spike-o-pult", .price = 320, .icon = 2},
    {.name = "Juggernaut", .price = 1800, .icon = 3},
};
static const Upgrade dart_monkey_data_3[] = {
    {.name = "Long Range Darts", .price = 90, .icon = 4},
    {.name = "Enhanced Eyesight", .price = 200, .icon = 5},
    {.name = "Crossbow", .price = 575, .icon = 6},
    {.name = "Sharp Shooter", .price = 2050, .icon = 7},
};
static const TowerProfile dart_monkey_data_4[] = {
    {
        .tiers = {0, 0, 0},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 8192,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2025,
                    .range = 10240,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2170,
                    .range = 12288,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1898,
                    .range = 15360,
                    .radius = 512,
                    .damage = 3,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 102400,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 4},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1266,
                    .range = 15360,
                    .radius = 512,
                    .damage = 6,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 153600,
                    .motion_flags = 2112,
                    .crit_every = 10,
                    .crit_damage = 50,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 8192,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2025,
                    .range = 10240,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2170,
                    .range = 12288,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1898,
                    .range = 15360,
                    .radius = 512,
                    .damage = 3,
                    .pierce = 7,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 102400,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 4},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1266,
                    .range = 15360,
                    .radius = 512,
                    .damage = 6,
                    .pierce = 7,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 153600,
                    .motion_flags = 2112,
                    .crit_every = 10,
                    .crit_damage = 50,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 8192,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2025,
                    .range = 10240,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 2170,
                    .range = 12288,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 89600,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1898,
                    .range = 15360,
                    .radius = 512,
                    .damage = 3,
                    .pierce = 12,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 102400,
                    .motion_flags = 2112,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 4},
        .range = 15360,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1266,
                    .range = 15360,
                    .radius = 512,
                    .damage = 6,
                    .pierce = 12,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 153600,
                    .motion_flags = 2112,
                    .crit_every = 10,
                    .crit_damage = 50,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 9421,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6900,
                    .life = 6000,
                    .range = 9421,
                    .radius = 1280,
                    .damage = 2,
                    .pierce = 18,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 1,
                    .speed = 38400,
                    .motion_flags = 2112,
                    .flags = A_BOUNCE,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 11469,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6900,
                    .life = 8100,
                    .range = 11469,
                    .radius = 1280,
                    .damage = 2,
                    .pierce = 18,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 1,
                    .speed = 38400,
                    .motion_flags = 2112,
                    .flags = A_BOUNCE,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 13517,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6900,
                    .life = 7594,
                    .range = 13517,
                    .radius = 1280,
                    .damage = 2,
                    .pierce = 18,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 1,
                    .speed = 51200,
                    .motion_flags = 2112,
                    .flags = A_BOUNCE,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 9421,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 6000,
                    .range = 9421,
                    .radius = 1792,
                    .damage = 2,
                    .pierce = 60,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .ceramic = 3,
                    .status_time = 900,
                    .fortified = 2,
                    .effects = dart_monkey_data_0,
                    .effect_count = 3,
                    .flags = A_BOUNCE | A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 0, 1},
        .range = 11469,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 8100,
                    .range = 11469,
                    .radius = 1792,
                    .damage = 2,
                    .pierce = 60,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .ceramic = 3,
                    .status_time = 900,
                    .fortified = 2,
                    .effects = dart_monkey_data_0,
                    .effect_count = 3,
                    .flags = A_BOUNCE | A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 0, 2},
        .range = 13517,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 7594,
                    .range = 13517,
                    .radius = 1792,
                    .damage = 2,
                    .pierce = 60,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .speed = 102400,
                    .motion_flags = 2112,
                    .ceramic = 3,
                    .status_time = 900,
                    .fortified = 2,
                    .effects = dart_monkey_data_1,
                    .effect_count = 3,
                    .flags = A_BOUNCE | A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
};

const TowerDef dart_monkey_def = {
    .name = "Dart Monkey",
    .price = 200,
    .caps = {4, 0, 4},
    .profile_count = 21,
    .profiles = dart_monkey_data_4,
    .upgrades = {dart_monkey_data_2, NULL, dart_monkey_data_3},
};
