#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/Druid
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/130494/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339169/

static const AttackEffect druid_data_0[] = {
    {.kind = EF_CLEANSE,
     .multiplier = 1000,
     .mutation = MUT_NONE,
     .chance = 1000,
     .modifier_flags = 32},
};
static const AttackEffect druid_data_1[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 2,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackEffect druid_data_2[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 2,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const AttackDef druid_data_3[] = {
    {
        .life = 27000,
        .range = 65535,
        .radius = 512,
        .damage = 1,
        .pierce = 20,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 17,
        .motion_flags = 2785,
        .refresh_pierce = 1800,
        .hit_reset = 1800,
        .effects = druid_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef druid_data_4[] = {
    {
        .life = 36000,
        .range = 65535,
        .radius = 512,
        .damage = 1,
        .pierce = 20,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 17,
        .motion_flags = 2785,
        .refresh_pierce = 1800,
        .hit_reset = 1800,
        .effects = druid_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef druid_data_5[] = {
    {
        .life = 27000,
        .range = 65535,
        .radius = 512,
        .damage = 1,
        .pierce = 20,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .motion_flags = 2785,
        .refresh_pierce = 1800,
        .hit_reset = 1800,
        .effects = druid_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect druid_data_6[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {51200, 1000, 0, 1000},
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {.kind = EF_CLEANSE,
     .multiplier = 1000,
     .mutation = MUT_NONE,
     .chance = 1000,
     .modifier_flags = 32},
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect druid_data_7[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {51200, 1000, 0, 1000},
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect druid_data_8[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {51200, 1000, 0, 1000},
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect druid_data_9[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {51200, 1000, 0, 1000},
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 2,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const Upgrade druid_data_10[] = {
    {.name = "Hard Thorns", .price = 350, .icon = 104},
    {.name = "Heart of Thunder", .price = 850, .icon = 105},
    {.name = "Druid of the Storm", .price = 1700, .icon = 106},
};
static const Upgrade druid_data_11[] = {
    {.name = "Thorn Swarm", .price = 250, .icon = 107},
    {.name = "Heart of Oak", .price = 350, .icon = 108},
    {.name = "Druid of the Jungle", .price = 1050, .icon = 109},
};
static const Upgrade druid_data_12[] = {
    {.name = "Druidic Reach", .price = 100, .icon = 110},
    {.name = "Heart of Vengeance", .price = 300, .icon = 111},
    {.name = "Druid of Wrath", .price = 600, .icon = 112},
};
static const TowerProfile
    druid_data_13[] =
        {
            {
                .tiers = {0, 0, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 1,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 0, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 0, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 0, 3},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_WRATH,
                .wrath_threshold = 10,
                .wrath_increment = 50,
                .wrath_max_stacks = 20,
                .wrath_timeout = 12000,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 3},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_WRATH,
                .wrath_threshold = 10,
                .wrath_increment = 50,
                .wrath_max_stacks = 20,
                .wrath_timeout = 12000,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 2, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {0, 2, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {0, 2, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {0, 2, 3},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_WRATH,
                .wrath_threshold = 10,
                .wrath_increment = 50,
                .wrath_max_stacks = 20,
                .wrath_timeout = 12000,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {0, 3, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 15600,
                            .life = 600,
                            .range = 65535,
                            .radius = 1024,
                            .damage = 65535,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .motion_flags = 2113,
                            .target_kind = 7,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 40,
                            .children = druid_data_3,
                            .child_count = 1,
                            .flags = A_NORMAL_ONLY | A_HITSCAN | A_EXPLOSION,
                            .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 15600,
                            .life = 600,
                            .range = 65535,
                            .radius = 1024,
                            .damage = 65535,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .motion_flags = 2113,
                            .target_kind = 7,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 40,
                            .children = druid_data_4,
                            .child_count = 1,
                            .flags = A_NORMAL_ONLY | A_HITSCAN | A_EXPLOSION,
                            .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 1,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .immunity = 17,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 15600,
                            .life = 600,
                            .range = 65535,
                            .radius = 1024,
                            .damage = 65535,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .motion_flags = 2113,
                            .target_kind = 7,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 40,
                            .children = druid_data_4,
                            .child_count = 1,
                            .flags = A_NORMAL_ONLY | A_HITSCAN | A_EXPLOSION,
                            .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 0, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 0, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 0, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 0, 3},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_WRATH,
                .wrath_threshold = 10,
                .wrath_increment = 50,
                .wrath_max_stacks = 20,
                .wrath_timeout = 12000,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 1, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 2, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {1, 3, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 15600,
                            .life = 600,
                            .range = 65535,
                            .radius = 1024,
                            .damage = 65535,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .motion_flags = 2113,
                            .target_kind = 7,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 40,
                            .children = druid_data_5,
                            .child_count = 1,
                            .flags = A_NORMAL_ONLY | A_HITSCAN | A_EXPLOSION,
                            .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 0, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                    },
            },
            {
                .tiers = {2, 0, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 11520,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                    },
            },
            {
                .tiers = {2, 0, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 11520,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                    },
            },
            {
                .tiers = {2, 0, 3},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_WRATH,
                .wrath_threshold = 10,
                .wrath_increment = 50,
                .wrath_max_stacks = 20,
                .wrath_timeout = 12000,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 11520,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                    },
            },
            {
                .tiers = {2, 1, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                    },
            },
            {
                .tiers = {2, 2, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_CHAIN | A_DEGROW,
                        },
                    },
            },
            {
                .tiers = {2, 3, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_CHAIN | A_DEGROW,
                        },
                        {
                            .period = 15600,
                            .life = 600,
                            .range = 65535,
                            .radius = 1024,
                            .damage = 65535,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .motion_flags = 2113,
                            .target_kind = 7,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 40,
                            .children = druid_data_5,
                            .child_count = 1,
                            .flags = A_NORMAL_ONLY | A_HITSCAN | A_EXPLOSION,
                            .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {3, 0, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                        {
                            .period = 15000,
                            .life = 6250,
                            .range = 8960,
                            .radius = 4096,
                            .pierce = 35,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 12,
                            .speed = 18432,
                            .motion_flags = 2112,
                            .push = 25600,
                            .homing_turn = 40960,
                            .homing_kind = 1,
                            .homing_range = 65535,
                            .homing_seek_angle = 65535,
                            .homing_flags = 5,
                            .effects = druid_data_6,
                            .effect_count = 5,
                            .flags = A_NORMAL_ONLY | A_WIND | A_HOMING,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB,
                        },
                    },
            },
            {
                .tiers = {3, 0, 1},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 11520,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                        {
                            .period = 15000,
                            .life = 8333,
                            .range = 11520,
                            .radius = 4096,
                            .pierce = 35,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 12,
                            .speed = 18432,
                            .motion_flags = 2112,
                            .push = 25600,
                            .homing_turn = 40960,
                            .homing_kind = 1,
                            .homing_range = 65535,
                            .homing_seek_angle = 65535,
                            .homing_flags = 5,
                            .effects = druid_data_7,
                            .effect_count = 4,
                            .flags = A_NORMAL_ONLY | A_WIND | A_HOMING,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB,
                        },
                    },
            },
            {
                .tiers = {3, 0, 2},
                .range = 11520,
                .buff_speed = 1000,
                .footprint = 1792,
                .life_speed_per = 10,
                .life_speed_cap = 40,
                .life_speed_base = 100,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 11520,
                            .damage = 1,
                            .pierce = 2,
                            .count = 5,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 11520,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                        {
                            .period = 15000,
                            .life = 8333,
                            .range = 11520,
                            .radius = 4096,
                            .pierce = 35,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 12,
                            .speed = 18432,
                            .motion_flags = 2112,
                            .push = 25600,
                            .homing_turn = 40960,
                            .homing_kind = 1,
                            .homing_range = 65535,
                            .homing_seek_angle = 65535,
                            .homing_flags = 5,
                            .effects = druid_data_8,
                            .effect_count = 5,
                            .flags = A_NORMAL_ONLY | A_WIND | A_HOMING,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB,
                        },
                    },
            },
            {
                .tiers = {3, 1, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .effects = druid_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .effects = druid_data_0,
                            .effect_count = 1,
                            .flags = A_CHAIN,
                        },
                        {
                            .period = 15000,
                            .life = 6250,
                            .range = 8960,
                            .radius = 4096,
                            .pierce = 35,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 12,
                            .speed = 18432,
                            .motion_flags = 2112,
                            .push = 25600,
                            .homing_turn = 40960,
                            .homing_kind = 1,
                            .homing_range = 65535,
                            .homing_seek_angle = 65535,
                            .homing_flags = 5,
                            .effects = druid_data_7,
                            .effect_count = 4,
                            .flags = A_NORMAL_ONLY | A_WIND | A_HOMING,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB,
                        },
                    },
            },
            {
                .tiers = {3, 2, 0},
                .range = 8960,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 1800,
                            .range = 8960,
                            .damage = 1,
                            .pierce = 2,
                            .count = 8,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .random_spread = 25000,
                            .speed = 87040,
                            .motion_flags = 2112,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_DEGROW,
                        },
                        {
                            .period = 13800,
                            .range = 8960,
                            .damage = 2,
                            .pierce = 5,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .motion_flags = 2113,
                            .chain_splits = 2,
                            .chain_range = 22016,
                            .chain_delay = 300,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_1,
                            .effect_count = 1,
                            .flags = A_CHAIN | A_DEGROW,
                        },
                        {
                            .period = 15000,
                            .life = 6250,
                            .range = 8960,
                            .radius = 4096,
                            .pierce = 35,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 12,
                            .speed = 18432,
                            .motion_flags = 2112,
                            .push = 25600,
                            .homing_turn = 40960,
                            .homing_kind = 1,
                            .homing_range = 65535,
                            .homing_seek_angle = 65535,
                            .homing_flags = 5,
                            .life_pierce_per = 10,
                            .life_pierce_cap = 100,
                            .effects = druid_data_9,
                            .effect_count = 5,
                            .flags = A_NORMAL_ONLY | A_WIND | A_DEGROW | A_HOMING,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB,
                        },
                    },
            },
};

const TowerDef druid_def = {
    .name = "Druid",
    .price = 400,
    .caps = {3, 3, 3},
    .profile_count = 34,
    .profiles = druid_data_13,
    .upgrades = {druid_data_10, druid_data_11, druid_data_12},
};
