#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/EngineerMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/128953/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339161/

static const AttackEffect engineer_monkey_data_0[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE,
        .layers = 1,
        .time = 6000,
        .mutation = MUT_STUN,
        .modifier_flags = 64,
    },
};

static const AttackCurvePoint engineer_monkey_data_2[] = {
    {0},
    {.x = 1, .y = 1},
    {.x = 2, .y = 1},
    {.x = 3, .y = 1},
    {.x = 4, .y = 2},
    {.x = 5, .y = 9},
    {.x = 6, .y = 22},
    {.x = 7, .y = 39},
    {.x = 8, .y = 59},
    {.x = 9, .y = 81},
    {.x = 10, .y = 104},
    {.x = 11, .y = 126},
    {.x = 12, .y = 146},
    {.x = 13, .y = 163},
    {.x = 14, .y = 177},
    {.x = 15, .y = 189},
    {.x = 16, .y = 200},
    {.x = 17, .y = 210},
    {.x = 18, .y = 218},
    {.x = 19, .y = 226},
    {.x = 20, .y = 232},
    {.x = 21, .y = 238},
    {.x = 22, .y = 243},
    {.x = 23, .y = 247},
    {.x = 24, .y = 250},
    {.x = 25, .y = 252},
    {.x = 26, .y = 254},
    {.x = 27, .y = 255},
    {.x = 28, .y = 256},
    {.x = 29, .y = 256},
};
static const AttackDef engineer_monkey_data_3[] = {
    {
        .life = 30000,
        .range = 10240,
        .radius = 5120,
        .pierce = 500,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_PIERCE,
        .camo = 1,
        .target_track_offset = 1024,
        .target_kind = 9,
        .expire_rounds = 65535,
        .motion_flags = 1,
        .collect_radius = 25600,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect engineer_monkey_data_4[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .exclude_tags = 1,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackDef engineer_monkey_data_5[] = {
    {
        .life = 30000,
        .range = 15360,
        .radius = 5120,
        .pierce = 500,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_PIERCE,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 1,
        .expire_rounds = 65535,
        .motion_flags = 1,
        .collect_radius = 25600,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect engineer_monkey_data_6[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackEffect engineer_monkey_data_7[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE,
        .layers = 1,
        .time = 6000,
        .mutation = MUT_STUN,
        .modifier_flags = 64,
    },
};
static const AttackEffect engineer_monkey_data_8[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 4,
        .mutation = MUT_NONE,
        .exclude_tags = 1,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackEffect engineer_monkey_data_9[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 11,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const AttackCurvePoint engineer_monkey_data_10[] = {
    {0},
    {.x = 1, .y = 17},
    {.x = 2, .y = 34},
    {.x = 3, .y = 50},
    {.x = 4, .y = 66},
    {.x = 5, .y = 81},
    {.x = 6, .y = 95},
    {.x = 7, .y = 109},
    {.x = 8, .y = 122},
    {.x = 9, .y = 134},
    {.x = 10, .y = 146},
    {.x = 11, .y = 157},
    {.x = 12, .y = 168},
    {.x = 13, .y = 178},
    {.x = 14, .y = 188},
    {.x = 15, .y = 196},
    {.x = 16, .y = 205},
    {.x = 17, .y = 212},
    {.x = 18, .y = 219},
    {.x = 19, .y = 226},
    {.x = 20, .y = 231},
    {.x = 21, .y = 237},
    {.x = 22, .y = 241},
    {.x = 23, .y = 245},
    {.x = 24, .y = 248},
    {.x = 25, .y = 251},
    {.x = 26, .y = 253},
    {.x = 27, .y = 255},
    {.x = 28, .y = 256},
    {.x = 29, .y = 256},
};
static const AttackDef engineer_monkey_data_11[] = {
    {
        .life = 51000,
        .range = 15360,
        .radius = 1792,
        .pierce = 10,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 1,
        .motion_flags = 1089,
        .effects = engineer_monkey_data_9,
        .effect_count = 1,
        .flags = A_FOAM | A_DECAMO | A_DEGROW,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackDef engineer_monkey_data_12[] = {
    {
        .life = 51000,
        .range = 15360,
        .radius = 1792,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 1,
        .motion_flags = 1089,
        .effects = engineer_monkey_data_9,
        .effect_count = 1,
        .flags = A_FOAM | A_DECAMO | A_DEGROW,
        .target_flags = AT_THROUGH_WALLS,
    },
};
static const AttackEffect engineer_monkey_data_13[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 11,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE,
        .multiplier = 500,
        .time = 12000,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 2,
    },
};
static const AttackDef engineer_monkey_data_14[] = {
    {
        .life = 51000,
        .range = 15360,
        .radius = 1792,
        .pierce = 15,
        .count = 1,
        .slow = 500,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 1,
        .motion_flags = 1089,
        .status_time = 12000,
        .effects = engineer_monkey_data_13,
        .effect_count = 3,
        .flags = A_FOAM | A_DECAMO | A_DEGROW,
        .target_flags = AT_THROUGH_WALLS,
    },
};

static const TowerProfile engineer_monkey_data_18[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_19[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 1,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_20[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .emission_kind = 1,
                    .emission_start = -384,
                    .emission_span = 768,
                    .emission_y = 256,
                    .immunity = 1,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_21[] = {
    {
        .range = 12544,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 12544,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_22[] = {
    {
        .range = 12544,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 12544,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .fortified = 1,
                    .moab = 1,
                    .effects = engineer_monkey_data_6,
                    .effect_count = 2,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const AttackEffect engineer_monkey_data_23[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 11,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const TowerProfile engineer_monkey_data_24[] = {
    {
        .range = 12544,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5700,
                    .life = 1500,
                    .range = 12544,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .fortified = 1,
                    .moab = 1,
                    .effects = engineer_monkey_data_23,
                    .effect_count = 3,
                    .flags = A_SENTRY | A_DECAMO | A_DEGROW,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_25[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_26[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 1,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_27[] = {
    {
        .range = 11520,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1500,
                    .range = 11520,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 3,
                    .count = 1,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 1,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .status_time = 6000,
                    .status_layers = 1,
                    .effects = engineer_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_28[] = {
    {
        .range = 12544,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1500,
                    .range = 12544,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const TowerProfile engineer_monkey_data_29[] = {
    {
        .range = 12544,
        .footprint = 1024,
        .buff_speed = 1000,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2850,
                    .life = 1500,
                    .range = 12544,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .fortified = 1,
                    .moab = 1,
                    .effects = engineer_monkey_data_6,
                    .effect_count = 2,
                    .flags = A_SENTRY | 0,
                },
            },
    },
};
static const Upgrade engineer_monkey_data_30[] = {
    {.name = "Sentry Gun", .price = 500, .icon = 127},
    {.name = "Faster Engineering", .price = 400, .icon = 128},
    {.name = "Sprockets", .price = 575, .icon = 129},
};
static const Upgrade engineer_monkey_data_31[] = {
    {.name = "Larger Service Area", .price = 250, .icon = 130},
    {.name = "Deconstruction", .price = 350, .icon = 131},
    {.name = "Cleansing Foam", .price = 900, .icon = 132},
};
static const Upgrade engineer_monkey_data_32[] = {
    {.name = "Oversize Nails", .price = 450, .icon = 134},
    {.name = "Pin", .price = 220, .icon = 135},
    {.name = "Double Gun", .price = 450, .icon = 136},
    {.name = "Bloon Trap", .price = 3600, .icon = 137},
};
static const TowerProfile
    engineer_monkey_data_33[] =
        {
            {
                .tiers = {0, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {0, 0, 1},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {0, 0, 2},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 0, 3},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 0, 4},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 72000,
                            .life = 4294967295,
                            .range = 10240,
                            .radius = 2560,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .target_track_offset = 1024,
                            .target_kind = 9,
                            .expire_rounds = 65535,
                            .motion_flags = 1611,
                            .trap_capacity = 500,
                            .trap_cash_multiplier = 2000,
                            .trap_close_delay = 4500,
                            .curve_time = 5400,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_2,
                            .curve_count = 30,
                            .projectile_limit = 1,
                            .projectile_limit_delay = 16700,
                            .children = engineer_monkey_data_3,
                            .child_count = 1,
                            .effects = engineer_monkey_data_4,
                            .effect_count = 1,
                            .flags = A_NORMAL_ONLY | A_TRAP | A_RETURN,
                            .target_flags = AT_NO_MOAB | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {0, 1, 1},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {0, 1, 2},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 3},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {0, 1, 4},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 72000,
                            .life = 4294967295,
                            .range = 15360,
                            .radius = 2560,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .expire_rounds = 65535,
                            .motion_flags = 1611,
                            .trap_capacity = 500,
                            .trap_cash_multiplier = 2000,
                            .trap_close_delay = 4500,
                            .curve_time = 5400,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_2,
                            .curve_count = 30,
                            .projectile_limit = 1,
                            .projectile_limit_delay = 16700,
                            .children = engineer_monkey_data_5,
                            .child_count = 1,
                            .effects = engineer_monkey_data_4,
                            .effect_count = 1,
                            .flags = A_NORMAL_ONLY | A_TRAP | A_RETURN,
                            .target_flags = AT_NO_MOAB | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                    },
            },
            {
                .tiers = {0, 2, 1},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                    },
            },
            {
                .tiers = {0, 2, 2},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_7,
                            .effect_count = 3,
                        },
                    },
            },
            {
                .tiers = {0, 2, 3},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_7,
                            .effect_count = 3,
                        },
                    },
            },
            {
                .tiers = {0, 2, 4},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_7,
                            .effect_count = 3,
                        },
                        {
                            .period = 72000,
                            .life = 4294967295,
                            .range = 15360,
                            .radius = 2560,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .expire_rounds = 65535,
                            .motion_flags = 1611,
                            .trap_capacity = 500,
                            .trap_cash_multiplier = 2000,
                            .trap_close_delay = 4500,
                            .curve_time = 5400,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_2,
                            .curve_count = 30,
                            .projectile_limit = 1,
                            .projectile_limit_delay = 16700,
                            .children = engineer_monkey_data_5,
                            .child_count = 1,
                            .effects = engineer_monkey_data_8,
                            .effect_count = 1,
                            .flags = A_NORMAL_ONLY | A_TRAP | A_RETURN | A_DEFORT,
                            .target_flags = AT_NO_MOAB | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .round_start_rate = 250,
                .round_start_time = 6000,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 15360,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_spread = 1024,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_10,
                            .curve_count = 30,
                            .children = engineer_monkey_data_11,
                            .child_count = 1,
                            .flags = A_FOAM | A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 1},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .round_start_rate = 250,
                .round_start_time = 6000,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 15360,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_10,
                            .curve_count = 30,
                            .children = engineer_monkey_data_12,
                            .child_count = 1,
                            .flags = A_FOAM | A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 2},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .round_start_rate = 250,
                .round_start_time = 6000,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_7,
                            .effect_count = 3,
                        },
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 15360,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_10,
                            .curve_count = 30,
                            .children = engineer_monkey_data_14,
                            .child_count = 1,
                            .flags = A_FOAM | A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_18,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {1, 0, 1},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_19,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {1, 0, 2},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_19,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 0, 3},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_20,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {1, 0, 4},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_20,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 72000,
                            .life = 4294967295,
                            .range = 10240,
                            .radius = 2560,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .target_track_offset = 1024,
                            .target_kind = 9,
                            .expire_rounds = 65535,
                            .motion_flags = 1611,
                            .trap_capacity = 500,
                            .trap_cash_multiplier = 2000,
                            .trap_close_delay = 4500,
                            .curve_time = 5400,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_2,
                            .curve_count = 30,
                            .projectile_limit = 1,
                            .projectile_limit_delay = 16700,
                            .children = engineer_monkey_data_3,
                            .child_count = 1,
                            .effects = engineer_monkey_data_4,
                            .effect_count = 1,
                            .flags = A_NORMAL_ONLY | A_TRAP | A_RETURN,
                            .target_flags = AT_NO_MOAB | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_21,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {1, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_22,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                    },
            },
            {
                .tiers = {1, 3, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .round_start_rate = 250,
                .round_start_time = 6000,
                .support = S_SENTRY,
                .sub_period = 60000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_24,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                        {
                            .period = 12000,
                            .life = 30000,
                            .range = 15360,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_10,
                            .curve_count = 30,
                            .children = engineer_monkey_data_11,
                            .child_count = 1,
                            .flags = A_FOAM | A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_18,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {2, 0, 1},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_19,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {2, 0, 2},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_19,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {2, 0, 3},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_20,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {2, 0, 4},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_20,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                        {
                            .period = 36000,
                            .life = 4294967295,
                            .range = 10240,
                            .radius = 2560,
                            .pierce = 65535,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .target_track_offset = 1024,
                            .target_kind = 9,
                            .expire_rounds = 65535,
                            .motion_flags = 1611,
                            .trap_capacity = 500,
                            .trap_cash_multiplier = 2000,
                            .trap_close_delay = 4500,
                            .curve_time = 5400,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_2,
                            .curve_count = 30,
                            .projectile_limit = 1,
                            .projectile_limit_delay = 12500,
                            .children = engineer_monkey_data_3,
                            .child_count = 1,
                            .effects = engineer_monkey_data_4,
                            .effect_count = 1,
                            .flags = A_NORMAL_ONLY | A_TRAP | A_RETURN,
                            .target_flags = AT_NO_MOAB | AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_21,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {2, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_22,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                    },
            },
            {
                .tiers = {2, 3, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .round_start_rate = 250,
                .round_start_time = 6000,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_24,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 4200,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                        {
                            .period = 6000,
                            .life = 30000,
                            .range = 15360,
                            .radius = 256,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .speed = 64000,
                            .motion_flags = 71,
                            .curve_kind = 2,
                            .curve = engineer_monkey_data_10,
                            .curve_count = 30,
                            .children = engineer_monkey_data_11,
                            .child_count = 1,
                            .flags = A_FOAM | A_RETURN,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {3, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_25,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {3, 0, 1},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_26,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {3, 0, 2},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_27,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 10240,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 10240,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 8,
                            .count = 1,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 1,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .status_time = 6000,
                            .status_layers = 1,
                            .effects = engineer_monkey_data_0,
                            .effect_count = 1,
                        },
                    },
            },
            {
                .tiers = {3, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_28,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                        },
                    },
            },
            {
                .tiers = {3, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .support = S_SENTRY,
                .sub_period = 30000,
                .sub_life = 150000,
                .sub_profiles = engineer_monkey_data_29,
                .sub_profile_count = 1,
                .sub_min_radius = 2048,
                .sub_max_radius = 15360,
                .sub_placement_radius = 1536,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 2100,
                            .life = 1440,
                            .range = 15360,
                            .radius = 512,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 17,
                            .speed = 96000,
                            .motion_flags = 2112,
                            .fortified = 1,
                            .moab = 1,
                            .effects = engineer_monkey_data_6,
                            .effect_count = 2,
                        },
                    },
            },
};

const TowerDef engineer_monkey_def = {
    .name = "Engineer Monkey",
    .price = 350,
    .caps = {3, 3, 4},
    .profile_count = 39,
    .profiles = engineer_monkey_data_33,
    .upgrades = {engineer_monkey_data_30, engineer_monkey_data_31, engineer_monkey_data_32},
};
