#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/GlueGunner
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/128703/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339151/

static const AttackEffect glue_gunner_data_0[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 3,
        .multiplier = 500,
        .time = 66000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_1[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 3,
        .multiplier = 500,
        .time = 144000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_2[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 3,
        .multiplier = 250,
        .time = 144000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_3[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 3,
        .multiplier = 250,
        .time = 144000,
        .value = 5,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 2500,
        .time = 54000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1600,
        .mutation = MUT_GLUE,
        .tags = 4096,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DOT_MODIFIER,
        .multiplier = 375,
        .mutation = MUT_CORROSIVE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 16384,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_4[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 66000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_5[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 144000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_6[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 250,
        .time = 144000,
        .value = 1,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_7[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 250,
        .time = 144000,
        .value = 5,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 2500,
        .time = 54000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1600,
        .mutation = MUT_GLUE,
        .tags = 4096,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DOT_MODIFIER,
        .multiplier = 375,
        .mutation = MUT_CORROSIVE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 16384,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_8[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 66000,
        .value = 2,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 66000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_9[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 144000,
        .value = 2,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_10[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 250,
        .time = 144000,
        .value = 2,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_11[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 250,
        .time = 144000,
        .value = 2,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 12000,
        .value = 15622,
        .mutation = MUT_CORROSIVE,
        .auxiliary = {9, 0, 0, 0},
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 2500,
        .time = 54000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1600,
        .mutation = MUT_GLUE,
        .tags = 4096,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DOT_MODIFIER,
        .multiplier = 375,
        .mutation = MUT_CORROSIVE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 16384,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_12[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 66000,
        .value = 3,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 66000,
        .period = 3000,
        .value = 44189,
        .mutation = MUT_DISSOLVER,
        .auxiliary = {0, 2, 0, 0},
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
};
static const AttackEffect glue_gunner_data_13[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 500,
        .time = 144000,
        .value = 3,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 3000,
        .value = 44189,
        .mutation = MUT_DISSOLVER,
        .auxiliary = {0, 2, 0, 0},
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 3000,
        .value = 44189,
        .mutation = MUT_DISSOLVER,
        .auxiliary = {0, 2, 0, 0},
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect glue_gunner_data_14[] = {
    {
        .kind = EF_GLUE_LEVEL,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .multiplier = 250,
        .time = 144000,
        .value = 3,
        .mutation = MUT_GLUE,
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 3000,
        .value = 44189,
        .mutation = MUT_DISSOLVER,
        .auxiliary = {0, 2, 0, 0},
    },
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .damage = 1,
        .immunity = 64,
        .multiplier = 1000,
        .time = 144000,
        .period = 3000,
        .value = 44189,
        .mutation = MUT_DISSOLVER,
        .auxiliary = {0, 2, 0, 0},
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_GLUE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 1,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const Upgrade glue_gunner_data_15[] = {
    {.name = "Glue Soak", .price = 200, .icon = 37},
    {.name = "Corrosive Glue", .price = 300, .icon = 38},
    {.name = "Bloon Dissolver", .price = 2000, .icon = 39},
};
static const Upgrade glue_gunner_data_16[] = {
    {.name = "Stickier Glue", .price = 280, .icon = 40},
    {.name = "Stronger Glue", .price = 400, .icon = 41},
    {.name = "MOAB Glue", .price = 3600, .icon = 42},
};
static const TowerProfile glue_gunner_data_17[] = {
    {
        .tiers = {0, 0, 0},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 66000,
                    .status_layers = 3,
                    .effects = glue_gunner_data_0,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 3,
                    .effects = glue_gunner_data_1,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 3,
                    .effects = glue_gunner_data_2,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 2500,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 3,
                    .effects = glue_gunner_data_3,
                    .effect_count = 5,
                    .flags = A_GLUE,
                    .target_flags = AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 66000,
                    .status_layers = 65535,
                    .effects = glue_gunner_data_4,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .effects = glue_gunner_data_5,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .effects = glue_gunner_data_6,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_GLUE,
                    .target_flags = AT_NO_MOAB | AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 2500,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .effects = glue_gunner_data_7,
                    .effect_count = 5,
                    .flags = A_GLUE,
                    .target_flags = AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 66000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 12000,
                    .effects = glue_gunner_data_8,
                    .effect_count = 3,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 12000,
                    .effects = glue_gunner_data_9,
                    .effect_count = 4,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 12000,
                    .effects = glue_gunner_data_10,
                    .effect_count = 4,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 2500,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 12000,
                    .effects = glue_gunner_data_11,
                    .effect_count = 6,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE | AT_NO_BOSS,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 2,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 66000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 3000,
                    .effects = glue_gunner_data_12,
                    .effect_count = 3,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 2,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 3000,
                    .ceramic = 2,
                    .effects = glue_gunner_data_13,
                    .effect_count = 5,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3000,
                    .life = 2580,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 2,
                    .count = 1,
                    .slow = 250,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .status_time = 144000,
                    .status_layers = 65535,
                    .dot_damage = 1,
                    .dot_period = 3000,
                    .ceramic = 2,
                    .effects = glue_gunner_data_14,
                    .effect_count = 5,
                    .flags = A_GLUE | A_DOT,
                    .target_flags = AT_NO_GLUE,
                },
            },
    },
};

const TowerDef glue_gunner_def = {
    .name = "Glue Gunner",
    .price = 225,
    .caps = {3, 0, 3},
    .profile_count = 15,
    .profiles = glue_gunner_data_17,
    .upgrades = {glue_gunner_data_15, NULL, glue_gunner_data_16},
};
