#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/HeliPilot
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/129682/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339145/

static const AirMovement heli_pilot_data_1[] = {
    {
        .speed = 10240,
        .catchup_speed = 1000,
        .force_start = 68267,
        .force_end = 34133,
        .brake_force = 45511,
        .repel_force = 68267,
        .repel_radius = 7680,
        .slowdown_max = 3840,
        .slowdown_min = 3,
        .min_velocity = 10,
    },
};
static const AirMovement heli_pilot_data_2[] = {
    {
        .speed = 17920,
        .catchup_speed = 1000,
        .force_start = 119467,
        .force_end = 59733,
        .brake_force = 79644,
        .repel_force = 119467,
        .repel_radius = 7680,
        .slowdown_max = 3840,
        .slowdown_min = 3,
        .min_velocity = 10,
    },
};
static const AttackEffect heli_pilot_data_3[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 8192,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {38400, 1000, 0, 1000},
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_REMOVE_GLUE_ICE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_PIERCE_COST,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AirMovement heli_pilot_data_4[] = {
    {
        .speed = 10240,
        .catchup_speed = 1000,
        .force_start = 68267,
        .force_end = 34133,
        .brake_force = 45511,
        .repel_force = 68267,
        .repel_radius = 7680,
        .slowdown_max = 3840,
        .slowdown_min = 3,
        .min_velocity = 10,
        .pursuit_distance = 8192,
    },
};
static const AirMovement heli_pilot_data_5[] = {
    {
        .speed = 17920,
        .catchup_speed = 1000,
        .force_start = 119467,
        .force_end = 59733,
        .brake_force = 79644,
        .repel_force = 119467,
        .repel_radius = 7680,
        .slowdown_max = 3840,
        .slowdown_min = 3,
        .min_velocity = 10,
        .pursuit_distance = 8192,
    },
};
static const Upgrade heli_pilot_data_6[] = {
    {.name = "Quad Darts", .price = 800, .icon = 56},
    {.name = "Pursuit", .price = 500, .icon = 57},
    {.name = "Razor Rotors", .price = 1450, .icon = 58},
};
static const Upgrade heli_pilot_data_7[] = {
    {.name = "Bigger Jets", .price = 300, .icon = 59},
    {.name = "IFR", .price = 600, .icon = 60},
    {.name = "Downdraft", .price = 3500, .icon = 61},
};
static const TowerProfile
    heli_pilot_data_8[] =
        {
            {
                .tiers = {0, 0, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_1,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 1, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 2, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {0, 3, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 1080,
                            .life = 600,
                            .range = 65535,
                            .radius = 8192,
                            .pierce = 2,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .motion_flags = 65,
                            .push = 8192,
                            .effects = heli_pilot_data_3,
                            .effect_count = 4,
                            .flags = A_NORMAL_ONLY | A_WIND,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB | AT_NO_LEAD | AT_GLOBAL |
                                            AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
            {
                .tiers = {1, 0, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_1,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 1, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 2, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 3, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_2,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 1080,
                            .life = 600,
                            .range = 65535,
                            .radius = 8192,
                            .pierce = 2,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .motion_flags = 65,
                            .push = 8192,
                            .effects = heli_pilot_data_3,
                            .effect_count = 4,
                            .flags = A_NORMAL_ONLY | A_WIND,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB | AT_NO_LEAD | AT_GLOBAL |
                                            AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
            {
                .tiers = {2, 0, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_4,
                .air_pursuit = 1,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 1, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_5,
                .air_pursuit = 1,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 2, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_5,
                .air_pursuit = 1,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 3, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_5,
                .air_pursuit = 1,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 1080,
                            .life = 600,
                            .range = 65535,
                            .radius = 8192,
                            .pierce = 2,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .motion_flags = 65,
                            .push = 8192,
                            .effects = heli_pilot_data_3,
                            .effect_count = 4,
                            .flags = A_NORMAL_ONLY | A_WIND,
                            .target_flags = AT_NO_WIND | AT_NO_MOAB | AT_NO_LEAD | AT_GLOBAL |
                                            AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
            {
                .tiers = {3, 0, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_4,
                .air_pursuit = 1,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 2700,
                            .life = 600,
                            .range = 65535,
                            .radius = 8960,
                            .damage = 2,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .motion_flags = 2113,
                            .flags = A_AREA | A_ROTOR,
                            .target_flags = AT_GLOBAL | AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
            {
                .tiers = {3, 1, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_5,
                .air_pursuit = 1,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 2700,
                            .life = 600,
                            .range = 65535,
                            .radius = 8960,
                            .damage = 2,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .motion_flags = 2113,
                            .flags = A_AREA | A_ROTOR,
                            .target_flags = AT_GLOBAL | AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
            {
                .tiers = {3, 2, 0},
                .range = 5632,
                .buff_speed = 1000,
                .footprint_rectangle = 1,
                .footprint_x = 6912,
                .footprint_y = 6912,
                .support = S_AIR,
                .air_movement = heli_pilot_data_5,
                .air_pursuit = 1,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 3420,
                            .life = 6000,
                            .range = 10752,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 3,
                            .count = 2,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .emission_kind = 2,
                            .immunity = 17,
                            .speed = 66560,
                            .motion_flags = 2113,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 2700,
                            .life = 600,
                            .range = 65535,
                            .radius = 8960,
                            .damage = 2,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .camo = 1,
                            .motion_flags = 2113,
                            .flags = A_AREA | A_ROTOR,
                            .target_flags = AT_GLOBAL | AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                        },
                    },
            },
};

const TowerDef heli_pilot_def = {
    .name = "Heli Pilot",
    .price = 1500,
    .caps = {3, 3, 0},
    .profile_count = 15,
    .profiles = heli_pilot_data_8,
    .upgrades = {heli_pilot_data_6, heli_pilot_data_7, NULL},
};
