#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/IceMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153848/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339163/

static const AttackEffect ice_monkey_data_0[] = {
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 2,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_FREEZE_MODIFIER,
        .multiplier = 500,
        .mutation = MUT_ICE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect ice_monkey_data_1[] = {
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 3,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
};
static const AttackDef ice_monkey_data_2[] = {
    {
        .life = 300,
        .range = 11776,
        .radius = 5120,
        .damage = 1,
        .pierce = 40,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 5,
        .motion_flags = 2113,
        .status_time = 9000,
        .status_layers = 3,
        .status_cascade = 1,
        .effects = ice_monkey_data_1,
        .effect_count = 1,
        .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
        .target_flags = AT_NO_MOAB,
    },
};
static const AttackEffect ice_monkey_data_3[] = {
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 2,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 2,
        .multiplier = 500,
        .time = 4294967295,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_FREEZE_MODIFIER,
        .multiplier = 500,
        .mutation = MUT_ICE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect ice_monkey_data_4[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 2,
        .multiplier = 500,
        .time = 4294967295,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 2,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_FREEZE_MODIFIER,
        .multiplier = 500,
        .mutation = MUT_ICE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect ice_monkey_data_5[] = {
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 3,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 3,
        .multiplier = 500,
        .time = 4294967295,
        .mutation = MUT_NONE,
    },
};
static const AttackDef ice_monkey_data_6[] = {
    {
        .life = 300,
        .range = 11776,
        .radius = 5120,
        .damage = 1,
        .pierce = 40,
        .count = 1,
        .slow = 500,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 5,
        .motion_flags = 2113,
        .status_time = 4294967295,
        .status_layers = 3,
        .status_cascade = 1,
        .effects = ice_monkey_data_5,
        .effect_count = 2,
        .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
        .target_flags = AT_NO_MOAB,
    },
};
static const AttackDef ice_monkey_data_7[] = {
    {
        .life = 300,
        .range = 11776,
        .radius = 5120,
        .damage = 1,
        .pierce = 40,
        .count = 1,
        .slow = 500,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .camo = 1,
        .immunity = 4,
        .motion_flags = 2113,
        .status_time = 4294967295,
        .status_layers = 3,
        .status_cascade = 1,
        .effects = ice_monkey_data_5,
        .effect_count = 2,
        .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
        .target_flags = AT_NO_MOAB | AT_CAMO_PRIORITY,
    },
};
static const AttackDef ice_monkey_data_8[] = {
    {
        .life = 480,
        .range = 6400,
        .radius = 512,
        .damage = 2,
        .pierce = 3,
        .count = 3,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_POP,
        .camo = 1,
        .target_kind = 4,
        .spread = 360,
        .immunity = 1,
        .speed = 64000,
        .motion_flags = 2112,
        .flags = A_RADIAL,
    },
};
static const AttackEffect ice_monkey_data_9[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 2,
        .multiplier = 500,
        .time = 4294967295,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 2,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackDef ice_monkey_data_10[] = {
    {
        .life = 480,
        .range = 8192,
        .radius = 512,
        .damage = 2,
        .pierce = 3,
        .count = 3,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_POP,
        .camo = 1,
        .target_kind = 4,
        .spread = 360,
        .immunity = 1,
        .speed = 64000,
        .motion_flags = 2112,
        .flags = A_RADIAL,
    },
};
static const AttackEffect ice_monkey_data_11[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const AttackDef ice_monkey_data_12[] = {
    {
        .life = 480,
        .range = 6400,
        .radius = 512,
        .damage = 2,
        .pierce = 3,
        .count = 3,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_POP,
        .camo = 1,
        .target_kind = 4,
        .spread = 360,
        .immunity = 1,
        .speed = 64000,
        .motion_flags = 2112,
        .effects = ice_monkey_data_11,
        .effect_count = 1,
        .flags = A_RADIAL | A_DECAMO | A_DEGROW,
    },
};
static const AttackEffect ice_monkey_data_13[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE | EF_CASCADE,
        .layers = 3,
        .multiplier = 1000,
        .time = 4294967295,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_REMOVE_DAMAGE_TYPE,
        .layers = 3,
        .immunity = 17,
        .multiplier = 1000,
        .time = 12000,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
    {
        .kind = EF_FREEZE,
        .flags = EF_CASCADE,
        .layers = 3,
        .multiplier = 1000,
        .time = 9000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 32,
    },
    {
        .kind = EF_VULNERABLE,
        .flags = EF_UNIQUE,
        .layers = 3,
        .damage = 1,
        .multiplier = 1000,
        .time = 12000,
        .mutation = MUT_ICE,
        .chance = 1000,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 500,
        .mutation = MUT_ICE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 4,
    },
    {
        .kind = EF_SLOW_MODIFIER,
        .multiplier = 750,
        .mutation = MUT_ICE,
        .tags = 1,
        .chance = 1000,
        .modifier_flags = 2,
    },
};
static const AttackDef ice_monkey_data_14[] = {
    {
        .life = 480,
        .range = 8192,
        .radius = 512,
        .damage = 2,
        .pierce = 3,
        .count = 3,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_POP,
        .camo = 1,
        .target_kind = 4,
        .spread = 360,
        .immunity = 1,
        .speed = 64000,
        .motion_flags = 2112,
        .effects = ice_monkey_data_11,
        .effect_count = 1,
        .flags = A_RADIAL | A_DECAMO | A_DEGROW,
    },
};
static const Upgrade ice_monkey_data_15[] = {
    {.name = "Permafrost", .price = 150, .icon = 30},
    {.name = "Cold Snap", .price = 350, .icon = 31},
    {.name = "Ice Shards", .price = 1500, .icon = 32},
    {.name = "Embrittlement", .price = 2300, .icon = 33},
};
static const Upgrade ice_monkey_data_16[] = {
    {.name = "Larger Radius", .price = 150, .icon = 34},
    {.name = "Re-Freeze", .price = 200, .icon = 35},
    {.name = "Cryo Cannon", .price = 1900, .icon = 36},
};
static const TowerProfile ice_monkey_data_17[] = {
    {
        .tiers = {0, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 5120,
                    .radius = 5120,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_0,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_0,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_0,
                    .effect_count = 2,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7200,
                    .life = 1200,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .children = ice_monkey_data_2,
                    .child_count = 1,
                    .flags = A_NORMAL_ONLY | A_EXPLOSION,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 5120,
                    .radius = 5120,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 4294967295,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_3,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_4,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 5,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_4,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7200,
                    .life = 1200,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .speed = 76800,
                    .motion_flags = 64,
                    .children = ice_monkey_data_6,
                    .child_count = 1,
                    .flags = A_NORMAL_ONLY | A_EXPLOSION,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 5120,
                    .radius = 5120,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_4,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_4,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 6912,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6912,
                    .radius = 6912,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .effects = ice_monkey_data_4,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 11776,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7200,
                    .life = 1200,
                    .range = 11776,
                    .radius = 1024,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .speed = 76800,
                    .motion_flags = 64,
                    .children = ice_monkey_data_7,
                    .child_count = 1,
                    .flags = A_NORMAL_ONLY | A_EXPLOSION,
                    .target_flags = AT_NO_MOAB | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 6400,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6400,
                    .radius = 6400,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .children = ice_monkey_data_8,
                    .child_count = 1,
                    .effects = ice_monkey_data_9,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE | A_DECAMO | A_DEGROW,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 8192,
                    .radius = 8192,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .children = ice_monkey_data_10,
                    .child_count = 1,
                    .effects = ice_monkey_data_9,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE | A_DECAMO | A_DEGROW,
                    .target_flags = AT_NO_MOAB | AT_NO_FROZEN,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 8192,
                    .radius = 8192,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 500,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 2,
                    .status_cascade = 1,
                    .children = ice_monkey_data_10,
                    .child_count = 1,
                    .effects = ice_monkey_data_9,
                    .effect_count = 3,
                    .flags = A_NORMAL_ONLY | A_AREA | A_FREEZE | A_DECAMO | A_DEGROW,
                    .target_flags = AT_NO_MOAB,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 6400,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 6400,
                    .radius = 6400,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 750,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 3,
                    .status_cascade = 1,
                    .vulnerability = 1,
                    .children = ice_monkey_data_12,
                    .child_count = 1,
                    .effects = ice_monkey_data_13,
                    .effect_count = 7,
                    .flags = A_AREA | A_FREEZE | A_DECAMO | A_DEGROW | A_VULNERABLE,
                },
            },
    },
    {
        .tiers = {4, 0, 1},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 8192,
                    .radius = 8192,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 750,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 3,
                    .status_cascade = 1,
                    .vulnerability = 1,
                    .children = ice_monkey_data_14,
                    .child_count = 1,
                    .effects = ice_monkey_data_13,
                    .effect_count = 7,
                    .flags = A_AREA | A_FREEZE | A_DECAMO | A_DEGROW | A_VULNERABLE,
                },
            },
    },
    {
        .tiers = {4, 0, 2},
        .range = 8192,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 14400,
                    .life = 300,
                    .range = 8192,
                    .radius = 8192,
                    .damage = 1,
                    .pierce = 40,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 750,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .target_kind = 4,
                    .immunity = 4,
                    .motion_flags = 2113,
                    .status_time = 9000,
                    .status_layers = 3,
                    .status_cascade = 1,
                    .vulnerability = 1,
                    .children = ice_monkey_data_14,
                    .child_count = 1,
                    .effects = ice_monkey_data_13,
                    .effect_count = 7,
                    .flags = A_AREA | A_FREEZE | A_DECAMO | A_DEGROW | A_VULNERABLE,
                },
            },
    },
};

const TowerDef ice_monkey_def = {
    .name = "Ice Monkey",
    .price = 400,
    .caps = {4, 0, 3},
    .profile_count = 18,
    .profiles = ice_monkey_data_17,
    .upgrades = {ice_monkey_data_15, NULL, ice_monkey_data_16},
};
