#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/MonkeyVillage
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153851/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/467957/

static const Upgrade monkey_village_data_0[] = {
    {.name = "Bigger Radius", .price = 400, .icon = 122},
    {.name = "Jungle Drums", .price = 1500, .icon = 123},
};
static const Upgrade monkey_village_data_1[] = {
    {.name = "Grow Blocker", .price = 250, .icon = 124},
    {.name = "Radar Scanner", .price = 2000, .icon = 125},
    {.name = "Monkey Intelligence Bureau", .price = 7500, .icon = 126},
};
static const TowerProfile monkey_village_data_2[] = {
    {
        .tiers = {0, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .attacks = {},
    },
    {
        .tiers = {0, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .regrow_block_range = 10240,
        .attacks = {},
    },
    {
        .tiers = {0, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .regrow_block_range = 10240,
        .attacks = {},
    },
    {
        .tiers = {0, 3, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .support_immunity = 31,
        .regrow_block_range = 10240,
        .attacks = {},
    },
    {
        .tiers = {1, 0, 0},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .attacks = {},
    },
    {
        .tiers = {1, 1, 0},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .regrow_block_range = 12288,
        .attacks = {},
    },
    {
        .tiers = {1, 2, 0},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .regrow_block_range = 12288,
        .attacks = {},
    },
    {
        .tiers = {1, 3, 0},
        .range = 12288,
        .buff_speed = 1000,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .support_immunity = 31,
        .regrow_block_range = 12288,
        .attacks = {},
    },
    {
        .tiers = {2, 0, 0},
        .range = 12288,
        .buff_speed = 850,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .attacks = {},
    },
    {
        .tiers = {2, 1, 0},
        .range = 12288,
        .buff_speed = 850,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .regrow_block_range = 12288,
        .attacks = {},
    },
    {
        .tiers = {2, 2, 0},
        .range = 12288,
        .buff_speed = 850,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .regrow_block_range = 12288,
        .attacks = {},
    },
    {
        .tiers = {2, 3, 0},
        .range = 12288,
        .buff_speed = 850,
        .footprint = 2816,
        .support = S_VILLAGE,
        .buff_range_multiplier = 1100,
        .support_camo = 1,
        .support_immunity = 31,
        .regrow_block_range = 12288,
        .attacks = {},
    },
};

const TowerDef monkey_village_def = {
    .name = "Monkey Village",
    .price = 1200,
    .caps = {2, 3, 0},
    .profile_count = 12,
    .profiles = monkey_village_data_2,
    .upgrades = {monkey_village_data_0, monkey_village_data_1, NULL},
};
