#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/MonkeyAce
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153849/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339153/

static const AttackEffect monkey_ace_data_0[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AirMovement monkey_ace_data_1[] = {
    {
        .speed = 15360,
        .rotation = 92160,
        .takeoff_time = 6000,
        .takeoff_exponent = 2500,
        .catchup_speed = 1200,
        .circle_radius = 20480,
    },
};

static const AttackDef monkey_ace_data_4[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7680,
        .damage = 18,
        .pierce = 4,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_MOAB_ONLY | A_AREA,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AirMovement monkey_ace_data_5[] = {
    {
        .speed = 19200,
        .rotation = 92160,
        .takeoff_time = 6000,
        .takeoff_exponent = 2500,
        .catchup_speed = 1200,
        .circle_radius = 20480,
    },
};

static const Upgrade monkey_ace_data_7[] = {
    {.name = "Rapid Fire", .price = 450, .icon = 50},
    {.name = "Lots More Darts", .price = 550, .icon = 51},
    {.name = "Fighter Plane", .price = 1000, .icon = 52},
};
static const Upgrade monkey_ace_data_8[] = {
    {.name = "Sharper Darts", .price = 500, .icon = 53},
    {.name = "Neva-Miss Targeting", .price = 2550, .icon = 55},
};
static const TowerProfile monkey_ace_data_9[] = {
    {
        .tiers = {0, 0, 0},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10080,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 5,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10080,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10080,
                    .life = 20000,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 46080,
                    .motion_flags = 2113,
                    .homing_turn = 2304,
                    .homing_acceleration = 12800,
                    .homing_max_speed = 89600,
                    .homing_min_speed = 5120,
                    .homing_kind = 2,
                    .homing_range = 65535,
                    .homing_seek_angle = 65535,
                    .homing_accelerate_angle = 256,
                    .homing_decelerate_angle = 7680,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL | A_HOMING,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 5,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 20000,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 46080,
                    .motion_flags = 2113,
                    .homing_turn = 2304,
                    .homing_acceleration = 12800,
                    .homing_max_speed = 89600,
                    .homing_min_speed = 5120,
                    .homing_kind = 2,
                    .homing_range = 65535,
                    .homing_seek_angle = 65535,
                    .homing_accelerate_angle = 256,
                    .homing_decelerate_angle = 7680,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL | A_HOMING,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 5,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_1,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 20000,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 46080,
                    .motion_flags = 2113,
                    .homing_turn = 2304,
                    .homing_acceleration = 12800,
                    .homing_max_speed = 89600,
                    .homing_min_speed = 5120,
                    .homing_kind = 2,
                    .homing_range = 65535,
                    .homing_seek_angle = 65535,
                    .homing_accelerate_angle = 256,
                    .homing_decelerate_angle = 7680,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL | A_HOMING,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_5,
        .attack_count = 2,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 5,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
                {
                    .period = 18000,
                    .life = 100800,
                    .range = 65535,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .emission_kind = 2,
                    .speed = 6400,
                    .motion_flags = 65,
                    .homing_turn = 6400,
                    .homing_kind = 1,
                    .homing_range = 65535,
                    .homing_seek_angle = 65535,
                    .homing_flags = 5,
                    .homing_acceleration = 40960,
                    .homing_max_speed = 102400,
                    .homing_max_turn = 128000,
                    .homing_turn_acceleration = 38400,
                    .children = monkey_ace_data_4,
                    .child_count = 1,
                    .flags = A_MOAB_ONLY | A_HOMING | A_EXPLOSION,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 5632,
        .buff_speed = 1000,
        .footprint_rectangle = 1,
        .footprint_x = 7168,
        .footprint_y = 4608,
        .support = S_AIR,
        .air_movement = monkey_ace_data_5,
        .attack_count = 2,
        .attacks =
            {
                {
                    .period = 7560,
                    .life = 8400,
                    .range = 5632,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 8,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 30720,
                    .motion_flags = 2113,
                    .effects = monkey_ace_data_0,
                    .effect_count = 1,
                    .flags = A_RADIAL,
                    .target_flags = AT_THROUGH_WALLS | AT_FIRE_WITHOUT_TARGET,
                },
                {
                    .period = 18000,
                    .life = 100800,
                    .range = 65535,
                    .radius = 1280,
                    .pierce = 1,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .emission_kind = 2,
                    .speed = 6400,
                    .motion_flags = 65,
                    .homing_turn = 6400,
                    .homing_kind = 1,
                    .homing_range = 65535,
                    .homing_seek_angle = 65535,
                    .homing_flags = 5,
                    .homing_acceleration = 40960,
                    .homing_max_speed = 102400,
                    .homing_max_turn = 128000,
                    .homing_turn_acceleration = 38400,
                    .children = monkey_ace_data_4,
                    .child_count = 1,
                    .flags = A_MOAB_ONLY | A_HOMING | A_EXPLOSION,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
};

const TowerDef monkey_ace_def = {
    .name = "Monkey Ace",
    .price = 800,
    .caps = {3, 0, 2},
    .profile_count = 11,
    .profiles = monkey_ace_data_9,
    .upgrades = {monkey_ace_data_7, NULL, monkey_ace_data_8},
};
