#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/MortarMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153852/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339171/

static const AttackDef mortar_monkey_data_0[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .damage = 2,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_1[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .damage = 2,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_2[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 1,
        .immunity = 8,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 11133,
        .mutation = MUT_NONE,
    },
};
static const AttackDef mortar_monkey_data_3[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .damage = 2,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_4[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const AttackEffect mortar_monkey_data_5[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 1,
        .immunity = 8,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 11133,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .exclude_tags = 2048,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackDef mortar_monkey_data_6[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 13312,
        .pierce = 50,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_4,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .damage = 2,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_5,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_7[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 6,
        .mutation = MUT_NONE,
        .exclude_tags = 7168,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackEffect mortar_monkey_data_8[] = {
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 3,
        .mutation = MUT_NONE,
        .chance = 1000,
    },
};
static const AttackEffect mortar_monkey_data_9[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 5,
        .immunity = 8,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 11133,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 4,
        .mutation = MUT_NONE,
        .exclude_tags = 7168,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackEffect mortar_monkey_data_10[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 20,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 9561,
        .mutation = MUT_NONE,
    },
};
static const AttackDef mortar_monkey_data_11[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_7,
        .effect_count = 1,
        .flags = A_MORTAR | A_DEGROW | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 13312,
        .pierce = 50,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_8,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .damage = 2,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 5,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_9,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 5120,
        .pierce = 25,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .dot_damage = 20,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_10,
        .effect_count = 1,
        .flags = A_MOAB_ONLY | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_12[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 2,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_13[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 2,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_14[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 2,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_15[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 18637,
        .pierce = 90,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_4,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 2,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_5,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_16[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_7,
        .effect_count = 1,
        .flags = A_MORTAR | A_DEGROW | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 18637,
        .pierce = 90,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_8,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 2,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 5,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_9,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .dot_damage = 20,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_10,
        .effect_count = 1,
        .flags = A_MOAB_ONLY | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_17[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_18[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_19[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_2,
        .effect_count = 1,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_20[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 18637,
        .pierce = 90,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_4,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 1,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_5,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_21[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 8,
        .immunity = 8,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 11133,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 4,
        .mutation = MUT_NONE,
        .exclude_tags = 7168,
        .chance = 1000,
        .modifier_flags = 32,
    },
};
static const AttackEffect mortar_monkey_data_22[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 25,
        .multiplier = 1000,
        .time = 23100,
        .period = 7500,
        .value = 9561,
        .mutation = MUT_NONE,
    },
};
static const AttackDef mortar_monkey_data_23[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_7,
        .effect_count = 1,
        .flags = A_MORTAR | A_DEGROW | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 18637,
        .pierce = 90,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .effects = mortar_monkey_data_8,
        .effect_count = 1,
        .flags = A_MORTAR | A_DECAMO | A_DEGROW,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 8,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_21,
        .effect_count = 2,
        .flags = A_AREA | A_MORTAR | A_DOT | A_DEFORT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 7168,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .dot_damage = 25,
        .dot_period = 7500,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_22,
        .effect_count = 1,
        .flags = A_MOAB_ONLY | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_24[] = {
    {
        .kind = EF_SLOW,
        .flags = EF_UNIQUE,
        .layers = 65535,
        .time = 3000,
        .mutation = MUT_STUN,
    },
    {.kind = EF_SLOW_MODIFIER,
     .mutation = MUT_STUN,
     .tags = 32,
     .chance = 1000,
     .modifier_flags = 2},
    {.kind = EF_SLOW_MODIFIER,
     .mutation = MUT_STUN,
     .tags = 128,
     .chance = 1000,
     .modifier_flags = 2},
};
static const AttackDef mortar_monkey_data_25[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 9728,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 4864,
        .pierce = 45,
        .count = 1,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .status_time = 3000,
        .status_layers = 65535,
        .effects = mortar_monkey_data_24,
        .effect_count = 3,
        .flags = A_NORMAL_ONLY | A_MORTAR | A_STUN,
        .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 14592,
        .damage = 1,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 64,
        .inner_radius = 500,
        .flags = A_MORTAR | A_AREA,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackDef mortar_monkey_data_26[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 9728,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .flags = A_AREA | A_MORTAR,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 4864,
        .pierce = 45,
        .count = 1,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .status_time = 3000,
        .status_layers = 65535,
        .effects = mortar_monkey_data_24,
        .effect_count = 3,
        .flags = A_NORMAL_ONLY | A_MORTAR | A_STUN,
        .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 14592,
        .damage = 1,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 64,
        .inner_radius = 500,
        .flags = A_MORTAR | A_AREA,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const AttackEffect mortar_monkey_data_27[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 2,
        .immunity = 8,
        .multiplier = 1000,
        .time = 23100,
        .period = 3750,
        .value = 11133,
        .mutation = MUT_NONE,
    },
};
static const AttackDef mortar_monkey_data_28[] = {
    {
        .life = 300,
        .range = 65535,
        .radius = 9728,
        .damage = 3,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 2112,
        .dot_damage = 2,
        .dot_period = 3750,
        .status_time = 23100,
        .status_layers = 65535,
        .effects = mortar_monkey_data_27,
        .effect_count = 1,
        .flags = A_AREA | A_MORTAR | A_DOT,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 4864,
        .pierce = 45,
        .count = 1,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .motion_flags = 64,
        .status_time = 3000,
        .status_layers = 65535,
        .effects = mortar_monkey_data_24,
        .effect_count = 3,
        .flags = A_NORMAL_ONLY | A_MORTAR | A_STUN,
        .target_flags = AT_NO_MOAB | AT_GLOBAL | AT_THROUGH_WALLS,
    },
    {
        .life = 300,
        .range = 65535,
        .radius = 14592,
        .damage = 1,
        .pierce = 45,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_EXHAUST,
        .camo = 1,
        .fixed_target = 1,
        .target_kind = 2,
        .immunity = 2,
        .motion_flags = 64,
        .inner_radius = 500,
        .flags = A_MORTAR | A_AREA,
        .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
    },
};
static const Upgrade mortar_monkey_data_29[] = {
    {.name = "Bigger Blast", .price = 300, .icon = 62},
    {.name = "Bloon Buster", .price = 500, .icon = 63},
    {.name = "Shell Shock", .price = 825, .icon = 64},
};
static const Upgrade mortar_monkey_data_30[] = {
    {.name = "Increased Accuracy", .price = 200, .icon = 65},
    {.name = "Burny Stuff", .price = 400, .icon = 66},
    {.name = "Signal Flare", .price = 1100, .icon = 67},
    {.name = "Shattering Shells", .price = 9500, .icon = 68},
};
static const TowerProfile mortar_monkey_data_31[] = {
    {
        .tiers = {0, 0, 0},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 4608,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_0,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_1,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_3,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_6,
                    .child_count = 2,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 0, 4},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_11,
                    .child_count = 4,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 4608,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_12,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_13,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_14,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_15,
                    .child_count = 2,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 4},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_16,
                    .child_count = 4,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 4608,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_17,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_18,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_19,
                    .child_count = 1,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_20,
                    .child_count = 2,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 4},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_23,
                    .child_count = 4,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 4608,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_25,
                    .child_count = 3,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_26,
                    .child_count = 3,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 7680,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 12000,
                    .life = 3000,
                    .range = 65535,
                    .radius = 512,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .fixed_target = 1,
                    .target_kind = 2,
                    .target_spread = 2048,
                    .motion_flags = 1,
                    .children = mortar_monkey_data_28,
                    .child_count = 3,
                    .flags = A_MORTAR,
                    .target_flags = AT_GLOBAL | AT_THROUGH_WALLS,
                },
            },
    },
};

const TowerDef mortar_monkey_def = {
    .name = "Mortar Monkey",
    .price = 600,
    .caps = {3, 0, 4},
    .profile_count = 18,
    .profiles = mortar_monkey_data_31,
    .upgrades = {mortar_monkey_data_29, NULL, mortar_monkey_data_30},
};
