#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/NinjaMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/130819/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339173/

static const AttackEffect ninja_monkey_data_0[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackEffect ninja_monkey_data_1[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 150,
        .auxiliary = {38400, 150, 500, 1000},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackEffect ninja_monkey_data_2[] = {
    {
        .kind = EF_WIND,
        .multiplier = 1000,
        .value = 25600,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 150,
        .auxiliary = {38400, 150, 500, 1000},
    },
    {
        .kind = EF_CLEANSE,
        .multiplier = 1000,
        .value = 1,
        .mutation = MUT_NONE,
        .chance = 1000,
        .modifier_flags = 32,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const Upgrade ninja_monkey_data_3[] = {
    {.name = "Ninja Discipline", .price = 350, .icon = 89},
    {.name = "Sharp Shurikens", .price = 350, .icon = 90},
    {.name = "Double Shot", .price = 900, .icon = 91},
    {.name = "Bloonjitsu", .price = 2750, .icon = 92},
};
static const Upgrade ninja_monkey_data_4[] = {
    {.name = "Distraction", .price = 250, .icon = 93},
    {.name = "Counter-Espionage", .price = 400, .icon = 94},
    {.name = "Shinobi Tactics", .price = 1200, .icon = 95},
};
static const TowerProfile ninja_monkey_data_5[] = {
    {
        .tiers = {0, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3720,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .effects = ninja_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3720,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .effects = ninja_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_WIND,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3720,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 3, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .support = S_SHINOBI,
        .support_stacks = 920,
        .support_max_stacks = 20,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3720,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .effects = ninja_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .effects = ninja_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_WIND,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 3, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .support = S_SHINOBI,
        .support_stacks = 920,
        .support_max_stacks = 20,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .effects = ninja_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .effects = ninja_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_WIND,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 3, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .support = S_SHINOBI,
        .support_stacks = 920,
        .support_max_stacks = 20,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 18,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 18,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_WIND,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 2,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 18,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 5,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 45,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 1, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 5,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 45,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_WIND,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 2, 0},
        .range = 10240,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2604,
                    .life = 3720,
                    .range = 10240,
                    .radius = 768,
                    .damage = 1,
                    .pierce = 4,
                    .count = 5,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 45,
                    .immunity = 17,
                    .speed = 76800,
                    .motion_flags = 2112,
                    .push = 25600,
                    .camo_damage = 2,
                    .random_spread = 10000,
                    .effects = ninja_monkey_data_2,
                    .effect_count = 3,
                    .flags = A_WIND | A_DECAMO,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
};

const TowerDef ninja_monkey_def = {
    .name = "Ninja Monkey",
    .price = 400,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = ninja_monkey_data_5,
    .upgrades = {ninja_monkey_data_3, ninja_monkey_data_4, NULL},
};
