#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/SniperMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153863/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/467954/

static const AttackEffect sniper_monkey_data_0[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackDef sniper_monkey_data_1[] = {
    {
        .life = 1200,
        .range = 65535,
        .radius = 51,
        .damage = 1,
        .pierce = 2,
        .count = 5,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_DAMAGE,
        .camo = 1,
        .spread = 45,
        .immunity = 17,
        .speed = 40960,
        .motion_flags = 2112,
        .camo_damage = 2,
        .effects = sniper_monkey_data_0,
        .effect_count = 1,
        .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
    },
};
static const AttackDef sniper_monkey_data_2[] = {
    {
        .life = 1200,
        .range = 65535,
        .radius = 51,
        .damage = 2,
        .pierce = 2,
        .count = 5,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_DAMAGE,
        .camo = 1,
        .spread = 45,
        .speed = 40960,
        .motion_flags = 2112,
        .camo_damage = 2,
        .effects = sniper_monkey_data_0,
        .effect_count = 1,
        .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
    },
};
static const AttackDef sniper_monkey_data_3[] = {
    {
        .life = 1200,
        .range = 65535,
        .radius = 51,
        .damage = 3,
        .pierce = 2,
        .count = 5,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_DAMAGE,
        .camo = 1,
        .spread = 45,
        .speed = 40960,
        .motion_flags = 2112,
        .camo_damage = 2,
        .effects = sniper_monkey_data_0,
        .effect_count = 1,
        .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
    },
};
static const AttackEffect sniper_monkey_data_4[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 50,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect sniper_monkey_data_5[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 50,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackDef sniper_monkey_data_6[] = {
    {
        .life = 1200,
        .range = 65535,
        .radius = 51,
        .damage = 4,
        .pierce = 2,
        .count = 5,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_DAMAGE,
        .camo = 1,
        .spread = 45,
        .speed = 40960,
        .motion_flags = 2112,
        .camo_damage = 2,
        .effects = sniper_monkey_data_0,
        .effect_count = 1,
        .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
    },
};
static const AttackEffect sniper_monkey_data_7[] = {
    {
        .kind = EF_MAIM,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {18000, 9000, 4500, 4500},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 50,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect sniper_monkey_data_8[] = {
    {
        .kind = EF_MAIM,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {18000, 9000, 4500, 4500},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 50,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackEffect sniper_monkey_data_9[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
    {
        .kind = EF_MAIM,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {12000, 6000, 3000, 3000},
    },
};
static const AttackDef sniper_monkey_data_10[] = {
    {
        .life = 1200,
        .range = 65535,
        .radius = 51,
        .damage = 6,
        .pierce = 2,
        .count = 5,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_DAMAGE,
        .camo = 1,
        .spread = 45,
        .speed = 40960,
        .motion_flags = 2112,
        .camo_damage = 2,
        .moab_stun = 12000,
        .bfb_stun = 6000,
        .effects = sniper_monkey_data_9,
        .effect_count = 2,
        .flags = A_STUN,
        .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
    },
};
static const Upgrade sniper_monkey_data_11[] = {
    {.name = "Full Metal Jacket", .price = 350, .icon = 43},
    {.name = "Large Calibre", .price = 1300, .icon = 44},
    {.name = "Deadly Precision", .price = 2200, .icon = 45},
    {.name = "Maim MOAB", .price = 6300, .icon = 46},
};
static const Upgrade sniper_monkey_data_12[] = {
    {.name = "Night Vision Goggles", .price = 250, .icon = 47},
    {.name = "Shrapnel Shot", .price = 450, .icon = 48},
    {.name = "Bouncing Bullet", .price = 2100, .icon = 49},
};
static const TowerProfile sniper_monkey_data_13[] = {
    {
        .tiers = {0, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 2,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .immunity = 17,
                    .motion_flags = 2112,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 2,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 2,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_1,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 12000,
                    .range = 65535,
                    .damage = 2,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .immunity = 17,
                    .motion_flags = 2112,
                    .chain_range = 10240,
                    .chain_delay = 600,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_1,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL | A_CHAIN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 4,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .motion_flags = 2112,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 4,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 4,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_2,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 12000,
                    .range = 65535,
                    .damage = 4,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .chain_range = 10240,
                    .chain_delay = 600,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_2,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL | A_CHAIN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 7,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .motion_flags = 2112,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 7,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 7,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_3,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 3, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 12000,
                    .range = 65535,
                    .damage = 7,
                    .pierce = 3,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .chain_range = 20480,
                    .chain_delay = 600,
                    .camo_damage = 2,
                    .children = sniper_monkey_data_3,
                    .child_count = 1,
                    .effects = sniper_monkey_data_0,
                    .effect_count = 1,
                    .flags = A_HITSCAN | A_SHRAPNEL | A_CHAIN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 20,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .motion_flags = 2112,
                    .ceramic = 50,
                    .effects = sniper_monkey_data_4,
                    .effect_count = 1,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 20,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .ceramic = 50,
                    .effects = sniper_monkey_data_5,
                    .effect_count = 2,
                    .flags = A_HITSCAN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 20,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .camo_damage = 2,
                    .ceramic = 50,
                    .children = sniper_monkey_data_6,
                    .child_count = 1,
                    .effects = sniper_monkey_data_5,
                    .effect_count = 2,
                    .flags = A_HITSCAN | A_SHRAPNEL,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 30,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .motion_flags = 2112,
                    .moab_stun = 18000,
                    .bfb_stun = 9000,
                    .ceramic = 50,
                    .effects = sniper_monkey_data_7,
                    .effect_count = 2,
                    .flags = A_HITSCAN | A_STUN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 1, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 30,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .moab_stun = 18000,
                    .bfb_stun = 9000,
                    .camo_damage = 2,
                    .ceramic = 50,
                    .effects = sniper_monkey_data_8,
                    .effect_count = 3,
                    .flags = A_HITSCAN | A_STUN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {4, 2, 0},
        .range = 5120,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 9540,
                    .life = 600,
                    .range = 65535,
                    .damage = 30,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .motion_flags = 2112,
                    .moab_stun = 18000,
                    .bfb_stun = 9000,
                    .camo_damage = 2,
                    .ceramic = 50,
                    .children = sniper_monkey_data_10,
                    .child_count = 1,
                    .effects = sniper_monkey_data_8,
                    .effect_count = 3,
                    .flags = A_HITSCAN | A_SHRAPNEL | A_STUN,
                    .target_flags = AT_GLOBAL | AT_CAMO_PRIORITY,
                },
            },
    },
};

const TowerDef sniper_monkey_def = {
    .name = "Sniper Monkey",
    .price = 350,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = sniper_monkey_data_13,
    .upgrades = {sniper_monkey_data_11, sniper_monkey_data_12, NULL},
};
