#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/SpikeFactory
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/129649/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339185/

static const AttackCurvePoint spike_factory_data_0[] = {
    {0},
    {.x = 1, .y = 1},
    {.x = 2, .y = 1},
    {.x = 3, .y = 1},
    {.x = 4, .y = 2},
    {.x = 5, .y = 9},
    {.x = 6, .y = 22},
    {.x = 7, .y = 39},
    {.x = 8, .y = 59},
    {.x = 9, .y = 81},
    {.x = 10, .y = 104},
    {.x = 11, .y = 126},
    {.x = 12, .y = 146},
    {.x = 13, .y = 163},
    {.x = 14, .y = 177},
    {.x = 15, .y = 189},
    {.x = 16, .y = 200},
    {.x = 17, .y = 210},
    {.x = 18, .y = 218},
    {.x = 19, .y = 226},
    {.x = 20, .y = 232},
    {.x = 21, .y = 238},
    {.x = 22, .y = 243},
    {.x = 23, .y = 247},
    {.x = 24, .y = 250},
    {.x = 25, .y = 252},
    {.x = 26, .y = 254},
    {.x = 27, .y = 255},
    {.x = 28, .y = 256},
    {.x = 29, .y = 256},
};
static const AttackEffect spike_factory_data_1[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 7,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackEffect spike_factory_data_2[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 4,
        .chance = 1000,
    },
};
static const Upgrade spike_factory_data_3[] = {
    {.name = "Bigger Stacks", .price = 800, .icon = 116},
    {.name = "White Hot Spikes", .price = 600, .icon = 117},
    {.name = "Spiked Balls", .price = 2300, .icon = 118},
};
static const Upgrade spike_factory_data_4[] = {
    {.name = "Faster Production", .price = 600, .icon = 119},
    {.name = "Even Faster Production", .price = 800, .icon = 120},
    {.name = "MOAB SHREDR", .price = 2500, .icon = 121},
};
static const TowerProfile spike_factory_data_5[] = {
    {
        .tiers = {0, 0, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10500,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 1, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 8400,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 2, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {0, 3, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .moab = 7,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_1,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10500,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 1, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 8400,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 2, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {1, 3, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .immunity = 17,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .moab = 7,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_1,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10500,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 1, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 8400,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 2, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {2, 3, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 10,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .moab = 7,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_1,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 10500,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 2,
                    .pierce = 11,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .ceramic = 3,
                    .fortified = 1,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_2,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 1, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 8400,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 2,
                    .pierce = 11,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .ceramic = 3,
                    .fortified = 1,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_2,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
    {
        .tiers = {3, 2, 0},
        .range = 8704,
        .buff_speed = 1000,
        .footprint = 2048,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6300,
                    .life = 300000,
                    .range = 8704,
                    .radius = 1536,
                    .damage = 2,
                    .pierce = 11,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .collision_interval = 500,
                    .target_track_offset = 768,
                    .target_kind = 8,
                    .motion_flags = 3403,
                    .hit_reset = 6,
                    .ceramic = 3,
                    .fortified = 1,
                    .curve_time = 5400,
                    .curve_kind = 2,
                    .curve = spike_factory_data_0,
                    .curve_count = 30,
                    .effects = spike_factory_data_2,
                    .effect_count = 1,
                    .flags = A_SPIKE | A_RETURN,
                    .target_flags = AT_THROUGH_WALLS,
                },
            },
    },
};

const TowerDef spike_factory_def = {
    .name = "Spike Factory",
    .price = 1000,
    .caps = {3, 3, 0},
    .profile_count = 15,
    .profiles = spike_factory_data_5,
    .upgrades = {spike_factory_data_3, spike_factory_data_4, NULL},
};
