#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/SuperMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/128590/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/467273/

static const AttackEffect super_monkey_data_0[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackEffect super_monkey_data_1[] = {
    {
        .kind = EF_KNOCKBACK,
        .multiplier = 1000,
        .time = 3000,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {300, 600, 1250, 0},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackEffect super_monkey_data_2[] = {
    {
        .kind = EF_KNOCKBACK,
        .multiplier = 1000,
        .time = 3000,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {300, 600, 1250, 0},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const AttackEffect super_monkey_data_3[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
    {
        .kind = EF_KNOCKBACK,
        .multiplier = 1000,
        .time = 3000,
        .mutation = MUT_NONE,
        .chance = 1000,
        .auxiliary = {300, 900, 1250, 0},
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 1,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 8,
        .chance = 1000,
    },
};
static const Upgrade super_monkey_data_4[] = {
    {.name = "Laser Blasts", .price = 2000, .icon = 83},
    {.name = "Plasma Blasts", .price = 2500, .icon = 84},
    {.name = "Sun Avatar", .price = 20000, .icon = 85},
};
static const Upgrade super_monkey_data_5[] = {
    {.name = "Knockback", .price = 3000, .icon = 86},
    {.name = "Ultravision", .price = 1200, .icon = 87},
    {.name = "Dark Knight", .price = 5600, .icon = 88},
};
static const TowerProfile super_monkey_data_6[] = {
    {
        .tiers = {0, 0, 0},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 12800,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 17,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .effects = super_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 12800,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 17,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .effects = super_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 13568,
                    .radius = 512,
                    .damage = 1,
                    .pierce = 1,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 17,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_2,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 13568,
                    .radius = 1024,
                    .damage = 1,
                    .pierce = 4,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 17,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .moab = 2,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_3,
                    .effect_count = 3,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1280,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 73,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .effects = super_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1280,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 73,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .effects = super_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 13568,
                    .radius = 1280,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 73,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_2,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 270,
                    .life = 3600,
                    .range = 13568,
                    .radius = 1792,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 73,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .moab = 2,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_3,
                    .effect_count = 3,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .effects = super_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .effects = super_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 13568,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 2,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_2,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 13568,
                    .radius = 2048,
                    .damage = 1,
                    .pierce = 5,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 64000,
                    .motion_flags = 2112,
                    .moab = 2,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_3,
                    .effect_count = 3,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 6,
                    .count = 3,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 30,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .effects = super_monkey_data_0,
                    .effect_count = 1,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 12800,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 12800,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 6,
                    .count = 3,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .spread = 30,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .effects = super_monkey_data_1,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 13568,
        .buff_speed = 1000,
        .footprint = 2816,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 180,
                    .life = 3600,
                    .range = 13568,
                    .radius = 1536,
                    .damage = 1,
                    .pierce = 6,
                    .count = 3,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .camo = 1,
                    .spread = 30,
                    .random_spread = 8000,
                    .immunity = 72,
                    .speed = 128000,
                    .motion_flags = 2112,
                    .status_time = 3000,
                    .camo_damage = 1,
                    .effects = super_monkey_data_2,
                    .effect_count = 2,
                    .flags = A_PUSH,
                    .target_flags = AT_CAMO_PRIORITY,
                },
            },
    },
};

const TowerDef super_monkey_def = {
    .name = "Super Monkey",
    .price = 2500,
    .caps = {3, 0, 3},
    .profile_count = 15,
    .profiles = super_monkey_data_6,
    .upgrades = {super_monkey_data_4, NULL, super_monkey_data_5},
};
