#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/TackShooter
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153864/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/339187/

static const Upgrade tack_shooter_data_0[] = {
    {.name = "Faster Shooting", .price = 150, .icon = 22},
    {.name = "Even Faster Shooting", .price = 220, .icon = 23},
    {.name = "Hot Shots", .price = 600, .icon = 24},
    {.name = "Ring of Fire", .price = 3500, .icon = 25},
};
static const Upgrade tack_shooter_data_1[] = {
    {.name = "More Tacks", .price = 150, .icon = 26},
    {.name = "Even More Tacks", .price = 150, .icon = 27},
    {.name = "Tack Sprayer", .price = 450, .icon = 28},
    {.name = "Overdrive", .price = 3200, .icon = 29},
};
static const TowerProfile tack_shooter_data_2[] = {
    {
        .tiers = {0, 0, 0},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6720,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {0, 0, 1},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6720,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 10,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {0, 0, 2},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6720,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {0, 0, 3},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 6720,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {0, 0, 4},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 2240,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {1, 0, 0},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5040,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {1, 0, 1},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5040,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 10,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {1, 0, 2},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5040,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {1, 0, 3},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 5040,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {1, 0, 4},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1680,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {2, 0, 0},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {2, 0, 1},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 10,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {2, 0, 2},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 1,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {2, 0, 3},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {2, 0, 4},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1260,
                    .life = 1200,
                    .range = 5888,
                    .damage = 1,
                    .pierce = 2,
                    .count = 16,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .immunity = 17,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {3, 0, 0},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 3,
                    .pierce = 1,
                    .count = 8,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {3, 0, 1},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 3,
                    .pierce = 1,
                    .count = 10,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {3, 0, 2},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 3780,
                    .life = 1200,
                    .range = 5888,
                    .damage = 3,
                    .pierce = 1,
                    .count = 12,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .spread = 360,
                    .speed = 40960,
                    .motion_flags = 2112,
                    .flags = A_RADIAL,
                },
            },
    },
    {
        .tiers = {4, 0, 0},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1890,
                    .life = 300,
                    .range = 5888,
                    .radius = 6400,
                    .damage = 5,
                    .pierce = 30,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 8,
                    .motion_flags = 2113,
                    .flags = A_AREA,
                },
            },
    },
    {
        .tiers = {4, 0, 1},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1890,
                    .life = 300,
                    .range = 5888,
                    .radius = 6400,
                    .damage = 6,
                    .pierce = 30,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 8,
                    .motion_flags = 2113,
                    .flags = A_AREA,
                },
            },
    },
    {
        .tiers = {4, 0, 2},
        .range = 5888,
        .buff_speed = 1000,
        .footprint = 1536,
        .attack_count = 1,
        .attacks =
            {
                {
                    .period = 1890,
                    .life = 300,
                    .range = 5888,
                    .radius = 6400,
                    .damage = 7,
                    .pierce = 30,
                    .count = 1,
                    .slow = 1000,
                    .moab_slow = 1000,
                    .trigger = TR_MAIN,
                    .target_kind = 4,
                    .immunity = 8,
                    .motion_flags = 2113,
                    .flags = A_AREA,
                },
            },
    },
};

const TowerDef tack_shooter_def = {
    .name = "Tack Shooter",
    .price = 260,
    .caps = {4, 0, 4},
    .profile_count = 21,
    .profiles = tack_shooter_data_2,
    .upgrades = {tack_shooter_data_0, NULL, tack_shooter_data_1},
};
