#include "mechanics/game.h"

// https://github.com/KyleDerZweite/btd6-atlas/tree/ded3155921d70cd83d803b4d70022000e4c37c6b/data/56.3-build-24829026/game-data/Towers/WizardMonkey
// Portrait: https://www.spriters-resource.com/pc_computer/bloonstd6/asset/153865/
// Model: https://models.spriters-resource.com/pc_computer/bloonstd6/asset/468035/

static const AttackDef wizard_monkey_data_0[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 2560,
        .damage = 1,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_CAMO_PRIORITY,
    },
};
static const AttackDef wizard_monkey_data_1[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 3584,
        .damage = 3,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_CAMO_PRIORITY,
    },
};
static const AttackEffect wizard_monkey_data_2[] = {
    {
        .kind = EF_DOT,
        .flags = EF_UNIQUE | EF_CASCADE | EF_ONLY_DAMAGED,
        .layers = 65535,
        .damage = 1,
        .immunity = 8,
        .multiplier = 1000,
        .time = 18600,
        .period = 9000,
        .value = 11133,
        .mutation = MUT_NONE,
    },
    {
        .kind = EF_DAMAGE_MODIFIER,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 2,
        .chance = 1000,
    },
};
static const AttackDef wizard_monkey_data_3[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 2560,
        .damage = 1,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackDef wizard_monkey_data_4[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 3584,
        .damage = 3,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackDef wizard_monkey_data_5[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 2560,
        .damage = 2,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackDef wizard_monkey_data_6[] = {
    {
        .life = 600,
        .range = 10240,
        .radius = 3584,
        .damage = 4,
        .pierce = 15,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackDef wizard_monkey_data_7[] = {
    {
        .life = 600,
        .range = 15360,
        .radius = 2560,
        .damage = 2,
        .pierce = 19,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackEffect wizard_monkey_data_8[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 10,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackEffect wizard_monkey_data_9[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 6,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const AttackDef wizard_monkey_data_10[] = {
    {
        .life = 600,
        .range = 15360,
        .radius = 2560,
        .damage = 2,
        .pierce = 19,
        .count = 1,
        .slow = 1000,
        .moab_slow = 1000,
        .trigger = TR_CONTACT,
        .immunity = 2,
        .motion_flags = 2113,
        .moab = 6,
        .effects = wizard_monkey_data_9,
        .effect_count = 1,
        .flags = A_AREA,
        .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
    },
};
static const AttackEffect wizard_monkey_data_11[] = {
    {
        .kind = EF_DAMAGE_MODIFIER,
        .damage = 2,
        .multiplier = 1000,
        .mutation = MUT_NONE,
        .tags = 1,
        .chance = 1000,
    },
};
static const Upgrade wizard_monkey_data_12[] = {
    {.name = "Guided Magic", .price = 175, .icon = 76},
    {.name = "Arcane Blast", .price = 450, .icon = 77},
    {.name = "Arcane Mastery", .price = 1450, .icon = 78},
    {.name = "Arcane Spike", .price = 10000, .icon = 79},
};
static const Upgrade wizard_monkey_data_13[] = {
    {.name = "Fireball", .price = 300, .icon = 80},
    {.name = "Wall of Fire", .price = 800, .icon = 81},
    {.name = "Dragon's Breath", .price = 3300, .icon = 82},
};
static const TowerProfile
    wizard_monkey_data_14[] =
        {
            {
                .tiers = {0, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {0, 1, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 2400,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .children = wizard_monkey_data_0,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {0, 2, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 2400,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .children = wizard_monkey_data_0,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 39000,
                            .life = 27000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .target_track_offset = 1024,
                            .target_kind = 9,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 900,
                            .hit_reset = 900,
                            .flags = A_WALL,
                        },
                    },
            },
            {
                .tiers = {0, 3, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 4,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 2400,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 2400,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 3,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .spread = 60,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2112,
                            .children = wizard_monkey_data_1,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 27000,
                            .life = 27000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 20,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .target_track_offset = 1024,
                            .target_kind = 9,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 600,
                            .hit_reset = 600,
                            .flags = A_WALL,
                        },
                        {
                            .period = 810,
                            .life = 2400,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 32000,
                            .motion_flags = 2112,
                            .dot_damage = 1,
                            .dot_period = 9000,
                            .status_time = 18600,
                            .status_layers = 65535,
                            .status_cascade = 1,
                            .effects = wizard_monkey_data_2,
                            .effect_count = 2,
                            .flags = A_DOT,
                            .target_flags = AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {1, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {1, 1, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_3,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {1, 2, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_3,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 39000,
                            .life = 39000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 900,
                            .hit_reset = 900,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {1, 3, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 4,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1024,
                            .damage = 1,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 3,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .spread = 60,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_4,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 27000,
                            .life = 39000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 20,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 600,
                            .hit_reset = 600,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 810,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 32000,
                            .motion_flags = 2113,
                            .dot_damage = 1,
                            .dot_period = 9000,
                            .status_time = 18600,
                            .status_layers = 65535,
                            .status_cascade = 1,
                            .effects = wizard_monkey_data_2,
                            .effect_count = 2,
                            .flags = A_DOT,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {2, 0, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {2, 1, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_5,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {2, 2, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_5,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 39000,
                            .life = 39000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 900,
                            .hit_reset = 900,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {2, 3, 0},
                .range = 10240,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 4,
                .attacks =
                    {
                        {
                            .period = 6600,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 4800,
                            .range = 10240,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 3,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .spread = 60,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_6,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 27000,
                            .life = 39000,
                            .range = 10240,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 20,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 600,
                            .hit_reset = 600,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                        {
                            .period = 810,
                            .life = 4800,
                            .range = 10240,
                            .radius = 1536,
                            .damage = 2,
                            .pierce = 3,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 32000,
                            .motion_flags = 2113,
                            .dot_damage = 1,
                            .dot_period = 9000,
                            .status_time = 18600,
                            .status_layers = 65535,
                            .status_cascade = 1,
                            .effects = wizard_monkey_data_2,
                            .effect_count = 2,
                            .flags = A_DOT,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {3, 0, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 3300,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 3,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {3, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 3300,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 3,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 8400,
                            .range = 15360,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_7,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {3, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 3300,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 3,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 73,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 8400,
                            .range = 15360,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_7,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 39000,
                            .life = 39000,
                            .range = 15360,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 900,
                            .hit_reset = 900,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
            {
                .tiers = {4, 0, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 1,
                .attacks =
                    {
                        {
                            .period = 1650,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 6,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .moab = 10,
                            .effects = wizard_monkey_data_8,
                            .effect_count = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {4, 1, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 2,
                .attacks =
                    {
                        {
                            .period = 1650,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 6,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .moab = 10,
                            .effects = wizard_monkey_data_8,
                            .effect_count = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 8400,
                            .range = 15360,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_10,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                    },
            },
            {
                .tiers = {4, 2, 0},
                .range = 15360,
                .buff_speed = 1000,
                .footprint = 1792,
                .attack_count = 3,
                .attacks =
                    {
                        {
                            .period = 1650,
                            .life = 8400,
                            .range = 15360,
                            .radius = 1536,
                            .damage = 6,
                            .pierce = 7,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 72,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .homing_turn = 92160,
                            .homing_kind = 1,
                            .homing_range = 20480,
                            .homing_seek_angle = 65535,
                            .homing_flags = 1,
                            .moab = 10,
                            .effects = wizard_monkey_data_8,
                            .effect_count = 1,
                            .flags = A_HOMING,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 13200,
                            .life = 8400,
                            .range = 15360,
                            .radius = 768,
                            .damage = 1,
                            .pierce = 1,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .immunity = 8,
                            .speed = 51200,
                            .motion_flags = 2113,
                            .children = wizard_monkey_data_10,
                            .child_count = 1,
                            .flags = A_EXPLOSION,
                            .target_flags = AT_THROUGH_WALLS | AT_CAMO_PRIORITY,
                        },
                        {
                            .period = 39000,
                            .life = 39000,
                            .range = 15360,
                            .radius = 3840,
                            .damage = 1,
                            .pierce = 10,
                            .count = 1,
                            .slow = 1000,
                            .moab_slow = 1000,
                            .trigger = TR_MAIN,
                            .fixed_target = 1,
                            .target_kind = 1,
                            .target_track_offset = 1024,
                            .immunity = 8,
                            .motion_flags = 2657,
                            .refresh_pierce = 900,
                            .hit_reset = 900,
                            .moab = 2,
                            .effects = wizard_monkey_data_11,
                            .effect_count = 1,
                            .flags = A_WALL,
                            .target_flags = AT_THROUGH_WALLS,
                        },
                    },
            },
};

const TowerDef wizard_monkey_def = {
    .name = "Wizard Monkey",
    .price = 250,
    .caps = {4, 3, 0},
    .profile_count = 18,
    .profiles = wizard_monkey_data_14,
    .upgrades = {wizard_monkey_data_12, wizard_monkey_data_13, NULL},
};
